(test
 (name test_main)
 (modules
  test_main
  test_source
  test_lexer
  test_preprocessor
  test_parser
  test_conditional_expression
  test_assert_directive
  test_help_directive
  test_predefined
  test_symbol_visibility
  test_diagnostic
  test_version
  test_corpus
  test_opcode_table_source
  test_primitive_type_source
  test_primitive_type
  test_operator_table_source
  test_operator_table
  test_compiler_option_source
  test_compiler_option
  test_intermediate_code_source
  test_intermediate_code
  test_function_flag_source
  test_function_flag
  test_bin_record_source
  test_bin_record)
 (libraries
  alcotest
  bin_record_tools
  compiler_option_tools
  function_flag_tools
  holyc_lib
  intermediate_code_tools
  opcode_table_tools
  operator_table_tools
  primitive_type_tools
  qcheck-alcotest)
 (deps
  ../third_party/TempleOS/Compiler/OpCodes.DD
  ../third_party/TempleOS/Compiler/CInit.HC
  ../third_party/TempleOS/Compiler/CExts.HC
  ../third_party/TempleOS/Compiler/CExcept.HC
  ../third_party/TempleOS/Compiler/CMain.HC
  ../third_party/TempleOS/Compiler/CMisc.HC
  ../third_party/TempleOS/Compiler/CompilerA.HH
  ../third_party/TempleOS/Compiler/BackFA.HC
  ../third_party/TempleOS/Compiler/BackLib.HC
  ../third_party/TempleOS/Compiler/BackC.HC
  ../third_party/TempleOS/Compiler/Asm.HC
  ../third_party/TempleOS/Compiler/AsmResolve.HC
  ../third_party/TempleOS/Compiler/Lex.HC
  ../third_party/TempleOS/Compiler/LexLib.HC
  ../third_party/TempleOS/Compiler/OptPass3.HC
  ../third_party/TempleOS/Compiler/OptPass6.HC
  ../third_party/TempleOS/Compiler/OptPass789A.HC
  ../third_party/TempleOS/Kernel/KernelA.HH
  ../third_party/TempleOS/Kernel/KernelB.HH
  ../third_party/TempleOS/Kernel/KernelC.HH
  ../third_party/TempleOS/Compiler/PrsLib.HC
  ../third_party/TempleOS/Compiler/PrsStmt.HC
  ../third_party/TempleOS/Compiler/PrsVar.HC
  ../third_party/TempleOS/Compiler/PrsExp.HC
  ../third_party/TempleOS/Adam/Gr/GrGlbls.HC
  ../third_party/TempleOS/Kernel/FunSeg.HC
  ../third_party/TempleOS/Kernel/KHashB.HC
  ../third_party/TempleOS/Kernel/KLoad.HC
  ../third_party/TempleOS/Kernel/KStart16.HC
  ../third_party/TempleOS/Kernel/KStart32.HC
  ../third_party/TempleOS/Kernel/StrPrint.HC
  ../third_party/TempleOS/Kernel/KUtils.HC
  ../third_party/TempleOS/Doc/HolyC.DD
  ../third_party/TempleOS/Doc/Options.DD
  (glob_files golden/*)
  (glob_files negative/*)))

(rule
 (alias runtest)
 (targets
  assert-warning.human.tokens.actual
  assert-warning.human.diagnostics.actual)
 (deps
  cli/assert-warning.hc
  cli/assert-warning.human.tokens
  cli/assert-warning.human.diagnostics)
 (action
  (progn
   (with-stdout-to
    assert-warning.human.tokens.actual
    (with-stderr-to
     assert-warning.human.diagnostics.actual
     (run %{exe:../bin/holyc.exe} preprocess cli/assert-warning.hc)))
   (diff cli/assert-warning.human.tokens assert-warning.human.tokens.actual)
   (diff
    cli/assert-warning.human.diagnostics
    assert-warning.human.diagnostics.actual))))

(rule
 (alias runtest)
 (targets
  assert-warning.json.tokens.actual
  assert-warning.json.diagnostics.actual)
 (deps
  cli/assert-warning.hc
  cli/assert-warning.json.tokens
  cli/assert-warning.json.diagnostics)
 (action
  (progn
   (with-stdout-to
    assert-warning.json.tokens.actual
    (with-stderr-to
     assert-warning.json.diagnostics.actual
     (run
      %{exe:../bin/holyc.exe}
      preprocess
      --format=json
      cli/assert-warning.hc)))
   (diff cli/assert-warning.json.tokens assert-warning.json.tokens.actual)
   (diff
    cli/assert-warning.json.diagnostics
    assert-warning.json.diagnostics.actual))))

(rule
 (alias runtest)
 (targets help-metadata.human.actual)
 (deps cli/help-metadata.hc cli/help-metadata.human)
 (action
  (progn
   (with-stdout-to
    help-metadata.human.actual
    (run
     %{exe:../bin/holyc.exe}
     preprocess
     --dump-help-metadata
     cli/help-metadata.hc))
   (diff cli/help-metadata.human help-metadata.human.actual))))

(rule
 (alias runtest)
 (targets help-metadata.json.actual)
 (deps cli/help-metadata.hc cli/help-metadata.json)
 (action
  (progn
   (with-stdout-to
    help-metadata.json.actual
    (run
     %{exe:../bin/holyc.exe}
     preprocess
     --dump-help-metadata
     --format=json
     cli/help-metadata.hc))
   (diff cli/help-metadata.json help-metadata.json.actual))))

(rule
 (alias runtest)
 (targets predefined-values.human.actual)
 (deps cli/predefined-values.hc cli/predefined-values.human)
 (action
  (progn
   (with-stdout-to
    predefined-values.human.actual
    (run
     %{exe:../bin/holyc.exe}
     preprocess
     --predefined-date=08/11/26
     --predefined-time=05:42:17
     --command-line-source
     cli/predefined-values.hc))
   (diff cli/predefined-values.human predefined-values.human.actual))))

(rule
 (alias runtest)
 (targets predefined-values.json.actual)
 (deps cli/predefined-values.hc cli/predefined-values.json)
 (action
  (progn
   (with-stdout-to
    predefined-values.json.actual
    (run
     %{exe:../bin/holyc.exe}
     preprocess
     --format=json
     --predefined-date=08/11/26
     --predefined-time=05:42:17
     --command-line-source
     cli/predefined-values.hc))
   (diff cli/predefined-values.json predefined-values.json.actual))))

(rule
 (alias runtest)
 (targets corpus-lexer.human.actual)
 (deps
  cli/corpus-lexer.human
  (source_tree ../third_party/TempleOS))
 (action
  (progn
   (with-stdout-to
    corpus-lexer.human.actual
    (run
     %{exe:../bin/holyc.exe}
     corpus
     lex
     --reference-root=%{env:DUNE_SOURCEROOT=}/third_party/TempleOS))
   (diff cli/corpus-lexer.human corpus-lexer.human.actual))))

(rule
 (alias runtest)
 (targets parse-globals.human.actual)
 (deps cli/parse-globals.hc cli/parse-globals.human)
 (action
  (progn
   (with-stdout-to
    parse-globals.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-globals.hc))
   (diff cli/parse-globals.human parse-globals.human.actual))))

(rule
 (alias runtest)
 (targets parse-globals.json.actual)
 (deps cli/parse-globals.hc cli/parse-globals.json)
 (action
  (progn
   (with-stdout-to
    parse-globals.json.actual
    (run %{exe:../bin/holyc.exe} dump-ast --format=json cli/parse-globals.hc))
   (diff cli/parse-globals.json parse-globals.json.actual))))

(rule
 (alias runtest)
 (targets parse-pointers.human.actual)
 (deps cli/parse-pointers.hc cli/parse-pointers.human)
 (action
  (progn
   (with-stdout-to
    parse-pointers.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-pointers.hc))
   (diff cli/parse-pointers.human parse-pointers.human.actual))))

(rule
 (alias runtest)
 (targets parse-pointers.json.actual)
 (deps cli/parse-pointers.hc cli/parse-pointers.json)
 (action
  (progn
   (with-stdout-to
    parse-pointers.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-pointers.hc))
   (diff cli/parse-pointers.json parse-pointers.json.actual))))

(rule
 (alias runtest)
 (targets parse-error.human.actual parse-error.human.stdout.actual)
 (deps cli/parse-error.hc cli/parse-error.human)
 (action
  (progn
   (with-stdout-to
    parse-error.human.stdout.actual
    (with-stderr-to
     parse-error.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-error.hc))))
   (diff cli/parse-error.human parse-error.human.actual))))

(rule
 (alias runtest)
 (targets parse-error.json.actual parse-error.json.stdout.actual)
 (deps cli/parse-error.hc cli/parse-error.json)
 (action
  (progn
   (with-stdout-to
    parse-error.json.stdout.actual
    (with-stderr-to
     parse-error.json.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse --format=json cli/parse-error.hc))))
   (diff cli/parse-error.json parse-error.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-pointer-errors.human.actual
  parse-pointer-errors.human.stdout.actual)
 (deps cli/parse-pointer-errors.hc cli/parse-pointer-errors.human)
 (action
  (progn
   (with-stdout-to
    parse-pointer-errors.human.stdout.actual
    (with-stderr-to
     parse-pointer-errors.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-pointer-errors.hc))))
   (diff cli/parse-pointer-errors.human parse-pointer-errors.human.actual))))

(rule
 (alias runtest)
 (targets
  parse-pointer-errors.json.actual
  parse-pointer-errors.json.stdout.actual)
 (deps cli/parse-pointer-errors.hc cli/parse-pointer-errors.json)
 (action
  (progn
   (with-stdout-to
    parse-pointer-errors.json.stdout.actual
    (with-stderr-to
     parse-pointer-errors.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-pointer-errors.hc))))
   (diff cli/parse-pointer-errors.json parse-pointer-errors.json.actual))))

(rule
 (alias runtest)
 (targets parse-comma-globals.human.actual)
 (deps cli/parse-comma-globals.hc cli/parse-comma-globals.human)
 (action
  (progn
   (with-stdout-to
    parse-comma-globals.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-comma-globals.hc))
   (diff cli/parse-comma-globals.human parse-comma-globals.human.actual))))

(rule
 (alias runtest)
 (targets parse-comma-globals.json.actual)
 (deps cli/parse-comma-globals.hc cli/parse-comma-globals.json)
 (action
  (progn
   (with-stdout-to
    parse-comma-globals.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-comma-globals.hc))
   (diff cli/parse-comma-globals.json parse-comma-globals.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-comma-errors.human.actual
  parse-comma-errors.human.stdout.actual)
 (deps cli/parse-comma-errors.hc cli/parse-comma-errors.human)
 (action
  (progn
   (with-stdout-to
    parse-comma-errors.human.stdout.actual
    (with-stderr-to
     parse-comma-errors.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-comma-errors.hc))))
   (diff cli/parse-comma-errors.human parse-comma-errors.human.actual))))

(rule
 (alias runtest)
 (targets
  parse-comma-errors.json.actual
  parse-comma-errors.json.stdout.actual)
 (deps cli/parse-comma-errors.hc cli/parse-comma-errors.json)
 (action
  (progn
   (with-stdout-to
    parse-comma-errors.json.stdout.actual
    (with-stderr-to
     parse-comma-errors.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-comma-errors.hc))))
   (diff cli/parse-comma-errors.json parse-comma-errors.json.actual))))

(rule
 (alias runtest)
 (targets parse-modifiers.human.actual)
 (deps cli/parse-modifiers.hc cli/parse-modifiers.human)
 (action
  (progn
   (with-stdout-to
    parse-modifiers.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-modifiers.hc))
   (diff cli/parse-modifiers.human parse-modifiers.human.actual))))

(rule
 (alias runtest)
 (targets parse-modifiers.json.actual)
 (deps cli/parse-modifiers.hc cli/parse-modifiers.json)
 (action
  (progn
   (with-stdout-to
    parse-modifiers.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-modifiers.hc))
   (diff cli/parse-modifiers.json parse-modifiers.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-modifier-error.human.actual
  parse-modifier-error.human.stdout.actual)
 (deps cli/parse-modifier-error.hc cli/parse-modifier-error.human)
 (action
  (progn
   (with-stdout-to
    parse-modifier-error.human.stdout.actual
    (with-stderr-to
     parse-modifier-error.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-modifier-error.hc))))
   (diff cli/parse-modifier-error.human parse-modifier-error.human.actual))))

(rule
 (alias runtest)
 (targets
  parse-modifier-error.json.actual
  parse-modifier-error.json.stdout.actual)
 (deps cli/parse-modifier-error.hc cli/parse-modifier-error.json)
 (action
  (progn
   (with-stdout-to
    parse-modifier-error.json.stdout.actual
    (with-stderr-to
     parse-modifier-error.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-modifier-error.hc))))
   (diff cli/parse-modifier-error.json parse-modifier-error.json.actual))))

(rule
 (alias runtest)
 (targets parse-bindings.human.actual)
 (deps cli/parse-bindings.hc cli/parse-bindings.human)
 (action
  (progn
   (with-stdout-to
    parse-bindings.human.actual
    (run %{exe:../bin/holyc.exe} parse --mode=aot cli/parse-bindings.hc))
   (diff cli/parse-bindings.human parse-bindings.human.actual))))

(rule
 (alias runtest)
 (targets parse-bindings.json.actual)
 (deps cli/parse-bindings.hc cli/parse-bindings.json)
 (action
  (progn
   (with-stdout-to
    parse-bindings.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --mode=aot
     --format=json
     cli/parse-bindings.hc))
   (diff cli/parse-bindings.json parse-bindings.json.actual))))

(rule
 (alias runtest)
 (targets parse-import-jit.human.actual parse-import-jit.human.stdout.actual)
 (deps cli/parse-import-jit.hc cli/parse-import-jit.human)
 (action
  (progn
   (with-stdout-to
    parse-import-jit.human.stdout.actual
    (with-stderr-to
     parse-import-jit.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-import-jit.hc))))
   (diff cli/parse-import-jit.human parse-import-jit.human.actual))))

(rule
 (alias runtest)
 (targets parse-import-jit.json.actual parse-import-jit.json.stdout.actual)
 (deps cli/parse-import-jit.hc cli/parse-import-jit.json)
 (action
  (progn
   (with-stdout-to
    parse-import-jit.json.stdout.actual
    (with-stderr-to
     parse-import-jit.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-import-jit.hc))))
   (diff cli/parse-import-jit.json parse-import-jit.json.actual))))

(rule
 (alias runtest)
 (targets parse-alternate-bindings.human.actual)
 (deps cli/parse-alternate-bindings.hc cli/parse-alternate-bindings.human)
 (action
  (progn
   (with-stdout-to
    parse-alternate-bindings.human.actual
    (run
     %{exe:../bin/holyc.exe}
     parse
     --mode=aot
     cli/parse-alternate-bindings.hc))
   (diff
    cli/parse-alternate-bindings.human
    parse-alternate-bindings.human.actual))))

(rule
 (alias runtest)
 (targets parse-alternate-bindings.json.actual)
 (deps cli/parse-alternate-bindings.hc cli/parse-alternate-bindings.json)
 (action
  (progn
   (with-stdout-to
    parse-alternate-bindings.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --mode=aot
     --format=json
     cli/parse-alternate-bindings.hc))
   (diff
    cli/parse-alternate-bindings.json
    parse-alternate-bindings.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-alternate-import-jit.human.actual
  parse-alternate-import-jit.human.stdout.actual)
 (deps
  cli/parse-alternate-import-jit.hc
  cli/parse-alternate-import-jit.human)
 (action
  (progn
   (with-stdout-to
    parse-alternate-import-jit.human.stdout.actual
    (with-stderr-to
     parse-alternate-import-jit.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-alternate-import-jit.hc))))
   (diff
    cli/parse-alternate-import-jit.human
    parse-alternate-import-jit.human.actual))))

(rule
 (alias runtest)
 (targets
  parse-alternate-import-jit.json.actual
  parse-alternate-import-jit.json.stdout.actual)
 (deps cli/parse-alternate-import-jit.hc cli/parse-alternate-import-jit.json)
 (action
  (progn
   (with-stdout-to
    parse-alternate-import-jit.json.stdout.actual
    (with-stderr-to
     parse-alternate-import-jit.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-alternate-import-jit.hc))))
   (diff
    cli/parse-alternate-import-jit.json
    parse-alternate-import-jit.json.actual))))

(rule
 (alias runtest)
 (targets parse-function-prototypes.human.actual)
 (deps cli/parse-function-prototypes.hc cli/parse-function-prototypes.human)
 (action
  (progn
   (with-stdout-to
    parse-function-prototypes.human.actual
    (run
     %{exe:../bin/holyc.exe}
     parse
     --mode=aot
     cli/parse-function-prototypes.hc))
   (diff
    cli/parse-function-prototypes.human
    parse-function-prototypes.human.actual))))

(rule
 (alias runtest)
 (targets parse-function-prototypes.json.actual)
 (deps cli/parse-function-prototypes.hc cli/parse-function-prototypes.json)
 (action
  (progn
   (with-stdout-to
    parse-function-prototypes.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --mode=aot
     --format=json
     cli/parse-function-prototypes.hc))
   (diff
    cli/parse-function-prototypes.json
    parse-function-prototypes.json.actual))))

(rule
 (alias runtest)
 (targets parse-default-parameters.human.actual)
 (deps cli/parse-default-parameters.hc cli/parse-default-parameters.human)
 (action
  (progn
   (with-stdout-to
    parse-default-parameters.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-default-parameters.hc))
   (diff
    cli/parse-default-parameters.human
    parse-default-parameters.human.actual))))

(rule
 (alias runtest)
 (targets parse-default-parameters.json.actual)
 (deps cli/parse-default-parameters.hc cli/parse-default-parameters.json)
 (action
  (progn
   (with-stdout-to
    parse-default-parameters.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-default-parameters.hc))
   (diff
    cli/parse-default-parameters.json
    parse-default-parameters.json.actual))))

(rule
 (alias runtest)
 (targets parse-arrays.human.actual)
 (deps cli/parse-arrays.hc cli/parse-arrays.human)
 (action
  (progn
   (with-stdout-to
    parse-arrays.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-arrays.hc))
   (diff cli/parse-arrays.human parse-arrays.human.actual))))

(rule
 (alias runtest)
 (targets parse-arrays.json.actual)
 (deps cli/parse-arrays.hc cli/parse-arrays.json)
 (action
  (progn
   (with-stdout-to
    parse-arrays.json.actual
    (run %{exe:../bin/holyc.exe} dump-ast --format=json cli/parse-arrays.hc))
   (diff cli/parse-arrays.json parse-arrays.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-array-error.human.actual
  parse-array-error.human.stdout.actual)
 (deps cli/parse-array-error.hc cli/parse-array-error.human)
 (action
  (progn
   (with-stdout-to
    parse-array-error.human.stdout.actual
    (with-stderr-to
     parse-array-error.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-array-error.hc))))
   (diff cli/parse-array-error.human parse-array-error.human.actual))))

(rule
 (alias runtest)
 (targets parse-array-error.json.actual parse-array-error.json.stdout.actual)
 (deps cli/parse-array-error.hc cli/parse-array-error.json)
 (action
  (progn
   (with-stdout-to
    parse-array-error.json.stdout.actual
    (with-stderr-to
     parse-array-error.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-array-error.hc))))
   (diff cli/parse-array-error.json parse-array-error.json.actual))))

(rule
 (alias runtest)
 (targets parse-intern-binding.human.actual)
 (deps cli/parse-intern-binding.hc cli/parse-intern-binding.human)
 (action
  (progn
   (with-stdout-to
    parse-intern-binding.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-intern-binding.hc))
   (diff cli/parse-intern-binding.human parse-intern-binding.human.actual))))

(rule
 (alias runtest)
 (targets parse-intern-binding.json.actual)
 (deps cli/parse-intern-binding.hc cli/parse-intern-binding.json)
 (action
  (progn
   (with-stdout-to
    parse-intern-binding.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-intern-binding.hc))
   (diff cli/parse-intern-binding.json parse-intern-binding.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-intern-error.human.actual
  parse-intern-error.human.stdout.actual)
 (deps cli/parse-intern-error.hc cli/parse-intern-error.human)
 (action
  (progn
   (with-stdout-to
    parse-intern-error.human.stdout.actual
    (with-stderr-to
     parse-intern-error.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-intern-error.hc))))
   (diff cli/parse-intern-error.human parse-intern-error.human.actual))))

(rule
 (alias runtest)
 (targets
  parse-intern-error.json.actual
  parse-intern-error.json.stdout.actual)
 (deps cli/parse-intern-error.hc cli/parse-intern-error.json)
 (action
  (progn
   (with-stdout-to
    parse-intern-error.json.stdout.actual
    (with-stderr-to
     parse-intern-error.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-intern-error.hc))))
   (diff cli/parse-intern-error.json parse-intern-error.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-function-prototype-error.human.actual
  parse-function-prototype-error.human.stdout.actual)
 (deps
  cli/parse-function-prototype-error.hc
  cli/parse-function-prototype-error.human)
 (action
  (progn
   (with-stdout-to
    parse-function-prototype-error.human.stdout.actual
    (with-stderr-to
     parse-function-prototype-error.human.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       cli/parse-function-prototype-error.hc))))
   (diff
    cli/parse-function-prototype-error.human
    parse-function-prototype-error.human.actual))))

(rule
 (alias runtest)
 (targets
  parse-function-prototype-error.json.actual
  parse-function-prototype-error.json.stdout.actual)
 (deps
  cli/parse-function-prototype-error.hc
  cli/parse-function-prototype-error.json)
 (action
  (progn
   (with-stdout-to
    parse-function-prototype-error.json.stdout.actual
    (with-stderr-to
     parse-function-prototype-error.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-function-prototype-error.hc))))
   (diff
    cli/parse-function-prototype-error.json
    parse-function-prototype-error.json.actual))))

(rule
 (alias runtest)
 (targets parse-function-modifiers.human.actual)
 (deps cli/parse-function-modifiers.hc cli/parse-function-modifiers.human)
 (action
  (progn
   (with-stdout-to
    parse-function-modifiers.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-function-modifiers.hc))
   (diff
    cli/parse-function-modifiers.human
    parse-function-modifiers.human.actual))))

(rule
 (alias runtest)
 (targets parse-function-modifiers.json.actual)
 (deps cli/parse-function-modifiers.hc cli/parse-function-modifiers.json)
 (action
  (progn
   (with-stdout-to
    parse-function-modifiers.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-function-modifiers.hc))
   (diff
    cli/parse-function-modifiers.json
    parse-function-modifiers.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-function-modifier-error.human.actual
  parse-function-modifier-error.human.stdout.actual)
 (deps
  cli/parse-function-modifier-error.hc
  cli/parse-function-modifier-error.human)
 (action
  (progn
   (with-stdout-to
    parse-function-modifier-error.human.stdout.actual
    (with-stderr-to
     parse-function-modifier-error.human.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       cli/parse-function-modifier-error.hc))))
   (diff
    cli/parse-function-modifier-error.human
    parse-function-modifier-error.human.actual))))

(rule
 (alias runtest)
 (targets
  parse-function-modifier-error.json.actual
  parse-function-modifier-error.json.stdout.actual)
 (deps
  cli/parse-function-modifier-error.hc
  cli/parse-function-modifier-error.json)
 (action
  (progn
   (with-stdout-to
    parse-function-modifier-error.json.stdout.actual
    (with-stderr-to
     parse-function-modifier-error.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-function-modifier-error.hc))))
   (diff
    cli/parse-function-modifier-error.json
    parse-function-modifier-error.json.actual))))

(rule
 (alias runtest)
 (targets parse-register-parameters.human.actual)
 (deps cli/parse-register-parameters.hc cli/parse-register-parameters.human)
 (action
  (progn
   (with-stdout-to
    parse-register-parameters.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-register-parameters.hc))
   (diff
    cli/parse-register-parameters.human
    parse-register-parameters.human.actual))))

(rule
 (alias runtest)
 (targets parse-register-parameters.json.actual)
 (deps cli/parse-register-parameters.hc cli/parse-register-parameters.json)
 (action
  (progn
   (with-stdout-to
    parse-register-parameters.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-register-parameters.hc))
   (diff
    cli/parse-register-parameters.json
    parse-register-parameters.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-register-parameter-error.human.actual
  parse-register-parameter-error.human.stdout.actual)
 (deps
  cli/parse-register-parameter-error.hc
  cli/parse-register-parameter-error.human)
 (action
  (progn
   (with-stdout-to
    parse-register-parameter-error.human.stdout.actual
    (with-stderr-to
     parse-register-parameter-error.human.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       cli/parse-register-parameter-error.hc))))
   (diff
    cli/parse-register-parameter-error.human
    parse-register-parameter-error.human.actual))))

(rule
 (alias runtest)
 (targets
  parse-register-parameter-error.json.actual
  parse-register-parameter-error.json.stdout.actual)
 (deps
  cli/parse-register-parameter-error.hc
  cli/parse-register-parameter-error.json)
 (action
  (progn
   (with-stdout-to
    parse-register-parameter-error.json.stdout.actual
    (with-stderr-to
     parse-register-parameter-error.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-register-parameter-error.hc))))
   (diff
    cli/parse-register-parameter-error.json
    parse-register-parameter-error.json.actual))))

(rule
 (alias runtest)
 (targets parse-function-pointer-parameters.human.actual)
 (deps
  cli/parse-function-pointer-parameters.hc
  cli/parse-function-pointer-parameters.human)
 (action
  (progn
   (with-stdout-to
    parse-function-pointer-parameters.human.actual
    (run
     %{exe:../bin/holyc.exe}
     parse
     cli/parse-function-pointer-parameters.hc))
   (diff
    cli/parse-function-pointer-parameters.human
    parse-function-pointer-parameters.human.actual))))

(rule
 (alias runtest)
 (targets parse-function-pointer-parameters.json.actual)
 (deps
  cli/parse-function-pointer-parameters.hc
  cli/parse-function-pointer-parameters.json)
 (action
  (progn
   (with-stdout-to
    parse-function-pointer-parameters.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-function-pointer-parameters.hc))
   (diff
    cli/parse-function-pointer-parameters.json
    parse-function-pointer-parameters.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-function-pointer-parameter-error.human.actual
  parse-function-pointer-parameter-error.human.stdout.actual)
 (deps
  cli/parse-function-pointer-parameter-error.hc
  cli/parse-function-pointer-parameter-error.human)
 (action
  (progn
   (with-stdout-to
    parse-function-pointer-parameter-error.human.stdout.actual
    (with-stderr-to
     parse-function-pointer-parameter-error.human.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       cli/parse-function-pointer-parameter-error.hc))))
   (diff
    cli/parse-function-pointer-parameter-error.human
    parse-function-pointer-parameter-error.human.actual))))

(rule
 (alias runtest)
 (targets
  parse-function-pointer-parameter-error.json.actual
  parse-function-pointer-parameter-error.json.stdout.actual)
 (deps
  cli/parse-function-pointer-parameter-error.hc
  cli/parse-function-pointer-parameter-error.json)
 (action
  (progn
   (with-stdout-to
    parse-function-pointer-parameter-error.json.stdout.actual
    (with-stderr-to
     parse-function-pointer-parameter-error.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-function-pointer-parameter-error.hc))))
   (diff
    cli/parse-function-pointer-parameter-error.json
    parse-function-pointer-parameter-error.json.actual))))

(rule
 (alias runtest)
 (targets parse-call-expression.human.actual)
 (deps cli/parse-call-expression.hc cli/parse-call-expression.human)
 (action
  (progn
   (with-stdout-to
    parse-call-expression.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-call-expression.hc))
   (diff cli/parse-call-expression.human parse-call-expression.human.actual))))

(rule
 (alias runtest)
 (targets parse-call-expression.json.actual)
 (deps cli/parse-call-expression.hc cli/parse-call-expression.json)
 (action
  (progn
   (with-stdout-to
    parse-call-expression.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-call-expression.hc))
   (diff cli/parse-call-expression.json parse-call-expression.json.actual))))

(rule
 (alias runtest)
 (targets parse-call-error.human.actual parse-call-error.human.stdout.actual)
 (deps cli/parse-call-error.hc cli/parse-call-error.human)
 (action
  (progn
   (with-stdout-to
    parse-call-error.human.stdout.actual
    (with-stderr-to
     parse-call-error.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-call-error.hc))))
   (diff cli/parse-call-error.human parse-call-error.human.actual))))

(rule
 (alias runtest)
 (targets parse-call-error.json.actual parse-call-error.json.stdout.actual)
 (deps cli/parse-call-error.hc cli/parse-call-error.json)
 (action
  (progn
   (with-stdout-to
    parse-call-error.json.stdout.actual
    (with-stderr-to
     parse-call-error.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-call-error.hc))))
   (diff cli/parse-call-error.json parse-call-error.json.actual))))

(rule
 (alias runtest)
 (targets parse-index-expression.human.actual)
 (deps cli/parse-index-expression.hc cli/parse-index-expression.human)
 (action
  (progn
   (with-stdout-to
    parse-index-expression.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-index-expression.hc))
   (diff
    cli/parse-index-expression.human
    parse-index-expression.human.actual))))

(rule
 (alias runtest)
 (targets parse-index-expression.json.actual)
 (deps cli/parse-index-expression.hc cli/parse-index-expression.json)
 (action
  (progn
   (with-stdout-to
    parse-index-expression.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-index-expression.hc))
   (diff cli/parse-index-expression.json parse-index-expression.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-index-error.human.actual
  parse-index-error.human.stdout.actual)
 (deps cli/parse-index-error.hc cli/parse-index-error.human)
 (action
  (progn
   (with-stdout-to
    parse-index-error.human.stdout.actual
    (with-stderr-to
     parse-index-error.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-index-error.hc))))
   (diff cli/parse-index-error.human parse-index-error.human.actual))))

(rule
 (alias runtest)
 (targets parse-index-error.json.actual parse-index-error.json.stdout.actual)
 (deps cli/parse-index-error.hc cli/parse-index-error.json)
 (action
  (progn
   (with-stdout-to
    parse-index-error.json.stdout.actual
    (with-stderr-to
     parse-index-error.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-index-error.hc))))
   (diff cli/parse-index-error.json parse-index-error.json.actual))))

(rule
 (alias runtest)
 (targets parse-member-expression.human.actual)
 (deps cli/parse-member-expression.hc cli/parse-member-expression.human)
 (action
  (progn
   (with-stdout-to
    parse-member-expression.human.actual
    (run %{exe:../bin/holyc.exe} parse cli/parse-member-expression.hc))
   (diff
    cli/parse-member-expression.human
    parse-member-expression.human.actual))))

(rule
 (alias runtest)
 (targets parse-member-expression.json.actual)
 (deps cli/parse-member-expression.hc cli/parse-member-expression.json)
 (action
  (progn
   (with-stdout-to
    parse-member-expression.json.actual
    (run
     %{exe:../bin/holyc.exe}
     dump-ast
     --format=json
     cli/parse-member-expression.hc))
   (diff
    cli/parse-member-expression.json
    parse-member-expression.json.actual))))

(rule
 (alias runtest)
 (targets
  parse-member-error.human.actual
  parse-member-error.human.stdout.actual)
 (deps cli/parse-member-error.hc cli/parse-member-error.human)
 (action
  (progn
   (with-stdout-to
    parse-member-error.human.stdout.actual
    (with-stderr-to
     parse-member-error.human.actual
     (with-accepted-exit-codes
      1
      (run %{exe:../bin/holyc.exe} parse cli/parse-member-error.hc))))
   (diff cli/parse-member-error.human parse-member-error.human.actual))))

(rule
 (alias runtest)
 (targets
  parse-member-error.json.actual
  parse-member-error.json.stdout.actual)
 (deps cli/parse-member-error.hc cli/parse-member-error.json)
 (action
  (progn
   (with-stdout-to
    parse-member-error.json.stdout.actual
    (with-stderr-to
     parse-member-error.json.actual
     (with-accepted-exit-codes
      1
      (run
       %{exe:../bin/holyc.exe}
       parse
       --format=json
       cli/parse-member-error.hc))))
   (diff cli/parse-member-error.json parse-member-error.json.actual))))
