(test
 (name test_main)
 (modules
  test_main
  test_source
  test_lexer
  test_diagnostic
  test_version
  test_opcode_table_source
  test_primitive_type_source
  test_primitive_type)
 (libraries
  alcotest
  holyc_lib
  opcode_table_tools
  primitive_type_tools
  qcheck-alcotest)
 (deps
  ../third_party/TempleOS/Compiler/OpCodes.DD
  ../third_party/TempleOS/Compiler/CInit.HC
  ../third_party/TempleOS/Kernel/KernelA.HH
  (glob_files golden/*)
  (glob_files negative/*)))
