open Holyc_lib
module Output = Test_integer_output
module G = Test_integer_globals

let gates =
  [
    ("literal", {|#exe {StreamPrint("42;");}|});
    ("joined fragments", {|#exe {StreamPrint("4");StreamPrint("2;");}|});
    ( "task function",
      {|#exe {I64 Add(I64 a,I64 b){return a+b;}StreamPrint("%d;",Add(20,22));}|}
    );
    ( "persistent task cell",
      {|#exe {I64 N=40;} #exe {N+=2;StreamPrint("%d;",N);}|} );
    ( "generated function",
      {|#exe {StreamPrint("I64 Generated(){return 42;}");} Generated();|} );
    ( "generated array",
      {|#exe {StreamPrint("I64 Values[2]={40,2};");} Values[0]+Values[1];|} );
    ("task loop", {|#exe {I64 N=0;while(N<42)++N;StreamPrint("%d;",N);}|});
    ("expression fragment", {|#exe {StreamPrint("40+");} 2;|});
    ( "formatted hexadecimal expression",
      {|I64 N=#exe {StreamPrint("0x%08tX",0x10000002A);};N;|} );
    ( "formatted dynamic width and precision",
      {|I64 N=#exe {StreamPrint("0x%0*.*tX",8,2,0x10000002A);};N;|} );
    ( "formatted string prefix",
      {|#exe {StreamPrint("%2ts","42ignored");StreamPrint(";");}|} );
    ("formatted packed prefix", {|#exe {StreamPrint("%*tc;",2,'42rest');}|});
    ( "formatted unsigned maximum reenters the lexer",
      {|#exe {StreamPrint("U64 Value=%u;",-1);}if(Value!=0xFFFFFFFFFFFFFFFF)1/0;42;|}
    );
    ( "quoted bytes generate a source string",
      {|#exe {StreamPrint("U8 Text[5]=\"%$$Q\";","a\"$$\n");}if(Text[0]!=97||Text[1]!=34||Text[2]!=36||Text[3]!=10||Text[4])1/0;42;|}
    );
    ( "decoded hexadecimal bytes generate a declaration",
      {|#exe {StreamPrint("%q","I64 Value=\\x34\\x32;");}Value;|} );
    ( "uppercase packed output generates a character constant",
      {|#exe {StreamPrint("U8 Drive='%C';",'c');}if(Drive!='C')1/0;42;|} );
    ( "repeated uppercase generates a packed constant",
      {|#exe {StreamPrint("U64 Value='%h*C';",4,'a');}if(Value!='AAAA')1/0;42;|}
    );
    ( "repeated spaces precede a generated declaration",
      {|#exe {StreamPrint("%h*cI64 Value=42;",3,' ');}Value;|} );
    ( "indexed list output selects a generated declaration",
      {|#exe {StreamPrint("%z",1,"I64 Value=1;\0I64 Value=42;\0");}Value;|} );
    ( "list aliases preserve generated initializer selection",
      {|#exe {StreamPrint("I64 Value=%z;",1,"0\0@alias\0(42)\0");}Value;|} );
    ( "missing list entry pads before generated source",
      {|#exe {StreamPrint("%3zI64 Value=42;",99,"A\0");}Value;|} );
  ]

let expect ?(modes = G.modes) value source () =
  List.iter
    (fun mode ->
      ignore (Output.run ~mode source |> Output.expect ~value:(Some value) ""))
    modes

let stream_exe_print_bridge () =
  ignore
    (Output.run ~mode:Preprocessor.Aot
       {|#exe {I64 N=StreamExePrint("40+2;");StreamPrint("%d;",N);}|}
    |> Output.expect ~value:(Some 42L) "");
  ignore
    (Output.run ~mode:Preprocessor.Jit
       {|#exe {I64 F(){return 40;}}#exe {I64 F(){return 42;}I64 N=StreamExePrint("F();");StreamPrint("%d;",N);}|}
    |> Output.expect ~value:(Some 42L) "");
  ignore
    (Output.run ~mode:Preprocessor.Aot
       {|#exe {I64 N=StreamExePrint("#exe {I64 N=StreamExePrint(\"40+2;\");StreamPrint(\"%%d;\",N);}");StreamPrint("%d;",N);}|}
    |> Output.expect ~value:(Some 42L) "");
  ignore
    (Output.run ~mode:Preprocessor.Jit
       {|#exe {StreamExePrint("I64 Generated(){return 42;}");}#exe {StreamPrint("%d;",Generated());}|}
    |> Output.expect ~value:(Some 42L) "");
  let failed =
    Output.run ~mode:Preprocessor.Aot
      {|#exe {StreamExePrint("Print(\"A\");1/0;");}|}
  in
  ignore (Output.fault ~output:"A" "HCIRVM0009" failed);
  let failed_progress = Option.get (integer_program_report_progress failed) in
  Alcotest.(check int)
    "failed StreamExePrint does not publish generated bytes" 0
    failed_progress.runtime.generated_bytes;
  let malformed =
    Output.run ~mode:Preprocessor.Aot {|#exe {StreamExePrint("%d");}|}
  in
  let malformed = Output.fault "HCIRVM0025" malformed in
  Alcotest.(check bool)
    "StreamExePrint formatting diagnostics name the provider" true
    (String.starts_with ~prefix:"StreamExePrint " malformed.message);
  ignore
    (Output.run ~mode:Preprocessor.Jit
       {|#exe {I64 N=StreamExePrint("%d;",40+2);StreamPrint("%d;",N);}|}
    |> Output.expect ~value:(Some 42L) "");
  let report =
    Output.run ~mode:Preprocessor.Jit
      {|#exe {StreamExePrint("StreamExePrint(\"42;\");");}|}
  in
  ignore (Output.fault "HCIRVM0027" report);
  let progress = Option.get (integer_program_report_progress report) in
  Alcotest.(check bool)
    "nested context check follows bounded formatting" true
    (progress.runtime.output_work > 0);
  Alcotest.(check int)
    "failed nested source does not publish generated bytes" 0
    progress.runtime.generated_bytes

let stream_exe_print_limits () =
  List.iter
    (fun mode ->
      let source =
        {|#exe {I64 N=StreamExePrint("40+2;");StreamPrint("%d;",N);}|}
      in
      let measured = Output.run ~mode source in
      ignore (Output.expect ~value:(Some 42L) "" measured);
      let progress = Option.get (integer_program_report_progress measured) in
      let steps = progress.runtime.executed_steps in
      let work = integer_program_report_output_work measured in
      ignore
        (Output.run ~mode ~max_steps:steps ~max_output_work:work source
        |> Output.expect ~value:(Some 42L) "");
      ignore
        (Output.run ~mode ~max_steps:(steps - 1) source
        |> Output.fault "HCIRVM0007");
      ignore
        (Output.run ~mode ~max_output_work:(work - 1) source
        |> Output.fault "HCIRVM0023");
      let nested =
        {|#exe {StreamExePrint("I64 F(){I64 X=42;return X;}F();");}|}
      in
      ignore
        (Output.run ~mode ~max_frame_bytes:24 ~max_call_depth:2 nested
        |> Output.expect ~value:None "");
      ignore
        (Output.run ~mode ~max_frame_bytes:23 ~max_call_depth:2 nested
        |> Output.fault "HCIRVM0011");
      ignore
        (Output.run ~mode ~max_frame_bytes:24 ~max_call_depth:1 nested
        |> Output.fault "HCIRVM0015"))
    G.modes

let stream_exe_print_contexts =
  [
    ( "StreamExePrint in a directive initializer",
      {|#exe {I64 N=StreamExePrint("40+2;");StreamPrint("%d;",N);}|} );
    ( "StreamExePrint in a directive saved default",
      {|#exe {U8 Format[6]="40+2;";I64 F(I64 N=StreamExePrint(Format)){return N;}StreamPrint("%d;",F());}|}
    );
    ( "StreamExePrint in a directive static initializer",
      {|#exe {I64 F(){static I64 N=StreamExePrint("40+2;");return N;}StreamPrint("%d;",F());}|}
    );
    ( "StreamExePrint in a directive array dimension",
      {|#exe {I64 N[StreamExePrint("2;")]={40,2};StreamPrint("%d;",N[0]+N[1]);}|}
    );
    ( "StreamExePrint in a directive aggregate offset",
      {|#exe {class C{U8 a;$$=StreamExePrint("16;");I64 b;};StreamPrint("%d;",sizeof(C)+18);}|}
    );
    ( "StreamExePrint publishes child defaults during a suspended default",
      {|#exe {U8 Format[41]="I64 Child(I64 N=40+2){return N;}Child();";I64 F(I64 N=StreamExePrint(Format)){return N;}StreamPrint("%d;",F());}|}
    );
    ( "StreamExePrint returns after its child's own directive",
      {|#exe {I64 N=StreamExePrint("#exe {StreamPrint(\"40+2;\");}");StreamPrint("%d;",N);}|}
    );
    ( "StreamExePrint resumes successive original directives",
      {|#exe {I64 N=StreamExePrint("20;");StreamPrint("%d+",N);}#exe {I64 N=StreamExePrint("22;");StreamPrint("%d;",N);}|}
    );
  ]

let stream_exe_print_jit_callers () =
  List.iter
    (fun source ->
      ignore
        (Output.run ~mode:Preprocessor.Jit source
        |> Output.expect ~value:(Some 42L) "before;child;after;"))
    [
      {|#exe {Print("before;");I64 N=StreamExePrint("Print(\"child;\");40+2;");Print("after;");StreamPrint("%d;",N);}|};
      {|#exe {I64 N=40;I64 F(I64 N){Print("before;");I64 X=StreamExePrint("Print(\"child;\");N+=2;N;");Print("after;");return X;}StreamPrint("%d;",F(0));}|};
      {|#exe {I64 F(I64 (*p)(U8 *fmt,...)=&StreamExePrint){Print("before;");I64 X=p("Print(\"child;\");40+2;");Print("after;");return X;}StreamPrint("%d;",F());}|};
    ]

let stream_exe_print_context_expiry () =
  List.iter
    (fun source ->
      let report = Output.run ~mode:Preprocessor.Jit source in
      let error = Output.fault "HCIRVM0027" report in
      Alcotest.(check bool)
        "inactive calls name their parser context" true
        (String.ends_with ~suffix:"requires an active #exe parser context"
           error.message);
      Alcotest.(check bool)
        "inactive calls finish formatting first" true
        (integer_program_report_output_work report > 0))
    [
      {|extern I64 StreamExePrint(U8 *fmt,...);StreamExePrint("40+2;");#exe {}|};
      {|#exe {I64 F(){return StreamExePrint("40+2;");}}F();|};
      {|#exe {I64 (*p)(U8 *fmt,...)=&StreamExePrint;}p("40+2;");|};
      {|#exe {I64 F(I64 (*p)(U8 *fmt,...)=&StreamExePrint){return p("40+2;");}}F();|};
      {|#exe {I64 F(){return StreamExePrint("40+2;");}}#exe {StreamPrint("0;");}F();|};
      {|#exe {I64 (*p)(U8 *fmt,...)=&StreamExePrint;p("I64 F(){return p(\"40+2;\");}F();");}|};
    ];
  List.iter
    (fun mode ->
      let report =
        Output.run ~mode
          {|#exe {StreamExePrint("StreamExePrint(\"40+2;\");");}|}
      in
      ignore (Output.fault "HCIRVM0027" report);
      let malformed =
        Output.run ~mode {|#exe {StreamExePrint("StreamExePrint(\"%%d\");");}|}
      in
      ignore (Output.fault "HCIRVM0025" malformed))
    G.modes

let stream_exe_print_declaration_limits () =
  List.iter
    (fun mode ->
      List.iter
        (fun (_, source) ->
          let measured = Output.run ~mode source in
          ignore (Output.expect "" measured);
          let progress =
            Option.get (integer_program_report_progress measured)
          in
          let steps = progress.runtime.executed_steps in
          let work = integer_program_report_output_work measured in
          let preparation =
            integer_program_report_preparation_work measured |> Option.get
          in
          ignore
            (Output.run ~mode ~max_steps:steps ~max_output_work:work
               ~max_initializer_steps:(max 1 preparation) source
            |> Output.expect "");
          ignore
            (Output.run ~mode ~max_steps:(steps - 1) source
            |> Output.fault "HCIRVM0007");
          ignore
            (Output.run ~mode ~max_output_work:(work - 1) source
            |> Output.fault "HCIRVM0023");
          if preparation > 1 then
            ignore
              (Output.run ~mode ~max_initializer_steps:(preparation - 1) source
              |> Output.fault "HCIRVM0007"))
        stream_exe_print_contexts)
    G.modes

let stream_exe_print_miscellaneous_default () =
  List.iter
    (fun mode ->
      Output.run ~mode
        {|#exe {I64 F(I64 N=StreamExePrint("40+2;")){return N;}StreamPrint("%d;",F());}|}
      |> Output.fault "HCRUN0006" |> ignore)
    G.modes

let stream_exe_print_source_limit () =
  let contents = {|#exe {StreamExePrint("40+2;");}|} in
  let run max_generated_bytes =
    let session = Session.create () in
    let source =
      Session.add_source session ~path:"stream-exe-print-limit.hc" ~contents
    in
    let config =
      match
        Preprocessor.Config.create ~compilation_mode:Preprocessor.Aot
          ~max_generated_bytes ()
      with
      | Ok config -> config
      | Error message -> Alcotest.fail message
    in
    run_integer_program_report ~max_steps:10_000 session ~config ~source
  in
  let exact = run 5 in
  ignore (Output.expect ~value:None "" exact);
  let exact_progress = Option.get (integer_program_report_progress exact) in
  Alcotest.(check int)
    "StreamExePrint source bytes are not published as generated bytes" 0
    exact_progress.runtime.generated_bytes;
  let below = run 4 in
  ignore (Output.fault "HCIRVM0028" below);
  let below_progress = Option.get (integer_program_report_progress below) in
  Alcotest.(check int)
    "rejected StreamExePrint source bytes remain unpublished" 0
    below_progress.runtime.generated_bytes

let saved_compiler_cases =
  [
    ( "saved compiler sizeof uses the original outer class",
      {|class Outer{I64 n;};#exe {I64 N=StreamExePrint("sizeof(Outer)+34;");StreamPrint("%d;",N);}|}
    );
    ( "saved compiler class survives a same-name task class",
      {|class C{I64 n;};#exe {class C{U8 n;};I64 N=StreamExePrint("sizeof(C)+34;");StreamPrint("%d;",N);}|}
    );
    ( "saved compiler defined excludes directive-only names",
      {|#exe {class TaskOnly{I64 n;};I64 F(){return 42;}I64 N=StreamExePrint("defined(TaskOnly)+defined(F)+42;");StreamPrint("%d;",N);}|}
    );
    ( "saved compiler macros use the enclosing definition table",
      "#define Saved 40+2\n\
       #exe {\n\
       #define Saved 17\n\
       I64 N=StreamExePrint(\"Saved;\");StreamPrint(\"%d;\",N);}" );
    ( "saved compiler child macros publish to outer input",
      {|#exe {StreamExePrint("#define ChildValue 40+2\n");}ChildValue;|} );
    ( "saved compiler child type publishes to outer input",
      {|#exe {StreamExePrint("class Child{I64 n;};");}sizeof(Child)+34;|} );
    ( "saved compiler child type survives successive directives",
      {|#exe {StreamExePrint("class Child{I64 n;};");}#exe {I64 N=StreamExePrint("sizeof(Child)+34;");StreamPrint("%d;",N);}|}
    );
    ( "saved compiler retains its own child cells",
      {|#exe {StreamExePrint("I64 ChildN=40;");I64 N=StreamExePrint("ChildN+=2;ChildN;");StreamPrint("%d;",N);}|}
    );
    ( "saved compiler retains original child functions and statics",
      {|#exe {StreamExePrint("I64 F(I64 n=40){static I64 x=2;return n+x;}");I64 N=StreamExePrint("F();");StreamPrint("%d;",N);}|}
    );
    ( "saved compiler child inheritance keeps the outer base",
      {|class Base{I64 n;};#exe {I64 N=StreamExePrint("class Child:Base{I64 n;};sizeof(Child)+26;");StreamPrint("%d;",N);}|}
    );
    ( "saved compiler child directive returns to task tables",
      {|#exe {I64 TaskN=2;I64 N=StreamExePrint("I64 ChildN=40;#exe {StreamPrint(\"ChildN+%%d;\",TaskN);}");StreamPrint("%d;",N);}|}
    );
    ( "saved compiler nested directive saves its child tables",
      {|#exe {I64 N=StreamExePrint("class C{I64 n;};#exe {I64 N=StreamExePrint(\"sizeof(C)+34;\");StreamPrint(\"%%d;\",N);}");StreamPrint("%d;",N);}|}
    );
  ]

let saved_compiler_limits () =
  let source =
    {|#exe {I64 F(){Print("before;");I64 N=StreamExePrint("I64 Values[2]={20,22};I64 G(){I64 N=Values[0]+Values[1];return N;}Print(\"child;\");G();");Print("after;");return N;}StreamPrint("%d;",F());}|}
  in
  List.iter
    (fun mode ->
      let measured = Output.run ~mode source in
      ignore (Output.expect "before;child;after;" measured);
      let progress = Option.get (integer_program_report_progress measured) in
      let steps = progress.runtime.executed_steps
      and work = integer_program_report_output_work measured
      and globals = progress.runtime.global_bytes
      and literals = progress.runtime.literal_bytes
      and preparation =
        Option.get (integer_program_report_preparation_work measured)
      in
      Alcotest.(check bool)
        "child initialization has reached preparation" true (preparation > 1);
      ignore
        (Output.run ~mode ~max_steps:steps ~max_output_work:work
           ~max_initializer_steps:preparation ~max_frame_bytes:40
           ~max_call_depth:3 ~max_global_bytes:globals
           ~max_literal_bytes:literals ~max_output_bytes:19 source
        |> Output.expect "before;child;after;");
      ignore
        (Output.run ~mode ~max_steps:(steps - 1) source
        |> Output.fault ~output:"before;child;after;" "HCIRVM0007");
      ignore
        (Output.run ~mode ~max_output_work:(work - 1) source
        |> Output.fault ~output:"before;child;after;" "HCIRVM0023");
      ignore
        (Output.run ~mode ~max_initializer_steps:(preparation - 1) source
        |> Output.fault ~output:"before;" "HCIRVM0007");
      ignore
        (Output.run ~mode ~max_frame_bytes:39 source
        |> Output.fault ~output:"before;" "HCIRVM0011");
      ignore
        (Output.run ~mode ~max_call_depth:2 source
        |> Output.fault ~output:"before;" "HCIRVM0015");
      ignore
        (Output.run ~mode ~max_global_bytes:(globals - 1) source
        |> Output.fault ~output:"before;" "HCIRVM0016");
      ignore
        (Output.run ~mode ~max_literal_bytes:(literals - 1) source
        |> Output.fault ~output:"before;" "HCIRVM0021");
      ignore
        (Output.run ~mode ~max_output_bytes:18 source
        |> Output.fault ~output:"before;child;" "HCIRVM0022"))
    G.modes

let saved_compiler_unsupported_original_storage () =
  List.iter
    (fun source ->
      ignore
        (Output.run ~mode:Preprocessor.Aot source |> Output.fault "HCRUN0003");
      ignore (Output.run ~mode:Preprocessor.Jit source |> Output.expect ""))
    [
      {|I64 N=40;#exe {I64 V=StreamExePrint("N+2;");StreamPrint("%d;",V);}|};
      {|I64 F(){return 42;}0;#exe {I64 V=StreamExePrint("F();");StreamPrint("%d;",V);}|};
    ];
  ignore
    (Output.run ~mode:Preprocessor.Jit
       {|I64 F(){return 42;}#exe {I64 V=StreamExePrint("F();");StreamPrint("%d;",V);}|}
    |> Output.fault "HCIRVM0030");
  List.iter
    (fun mode ->
      let error =
        Output.run ~mode
          {|I64 N;I64 F(){U8 N;#exe {I64 V=StreamExePrint("sizeof(N);");StreamPrint("%d;",V);}return 0;}42;|}
        |> Output.fault "HCRUN0004"
      in
      Alcotest.(check bool)
        "saved local cannot fall through to same-name global" true
        (String.ends_with
           ~suffix:"local sizeof has no original function publication"
           error.message))
    G.modes

let tests =
  List.map
    (fun (name, source) -> Alcotest.test_case name `Quick (expect 42L source))
    (gates @ stream_exe_print_contexts)
  @ List.map
      (fun (name, source) ->
        Alcotest.test_case name `Quick
          (expect ~modes:[ Preprocessor.Aot ] 42L source))
      saved_compiler_cases
  @ [
      Alcotest.test_case
        "saved compiler execution shares original work and frames" `Quick
        saved_compiler_limits;
      Alcotest.test_case
        "saved compiler keeps original runtime and local boundaries" `Quick
        saved_compiler_unsupported_original_storage;
      Alcotest.test_case "StreamExePrint requires an active parser context"
        `Quick stream_exe_print_bridge;
      Alcotest.test_case "StreamExePrint keeps JIT callers and output order"
        `Quick stream_exe_print_jit_callers;
      Alcotest.test_case "StreamExePrint context ends with its directive" `Quick
        stream_exe_print_context_expiry;
      Alcotest.test_case "StreamExePrint declaration work shares exact limits"
        `Quick stream_exe_print_declaration_limits;
      Alcotest.test_case
        "StreamExePrint keeps miscellaneous default copy boundary" `Quick
        stream_exe_print_miscellaneous_default;
      Alcotest.test_case "StreamExePrint shares task execution limits" `Quick
        stream_exe_print_limits;
      Alcotest.test_case "StreamExePrint source byte bound" `Quick
        stream_exe_print_source_limit;
      Alcotest.test_case
        "adjacent PutChars preserves target through argument lookahead" `Quick
        (expect 42L
           {|#exe {I64 Out=0;U0 PutChars(I64 a,I64 b){Out=a+b;}''40 2 #exe {U0 PutChars(I64 a=7){Out=a;}};I64 Before=Out;'';StreamPrint("%d;",Before+Out-7);}|});
      Alcotest.test_case
        "adjacent PutChars leaves completed comma to statement order" `Quick
        (expect 42L
           {|I64 Out=0;U0 PutChars(I64 a,I64 b=1){Out+=a+b;}''20,Out+=1;U0 Saved(){''19;}Saved;Out;|});
      Alcotest.test_case "PutChars consumes adjacent required arguments" `Quick
        (expect 42L
           {|I64 Out=0;U0 PutChars(I64 a,I64 b,I64 c){Out=a+b+c;}'' 20 20 2;I64 Top=Out;U0 Saved(){'A'-45 20 2;}Out=0;Saved;Top+Out-42;|});
      Alcotest.test_case
        "PutChars defaults leave following required values unconsumed" `Quick
        (expect 42L
           {|#exe {I64 N=38;I64 Out=0;U0 PutChars(I64 a,I64 b=++N,I64 c){Out=a+b+c;}N=0;'' 1 2;I64 Top=Out;U0 Saved(){'A'-64 2;}Out=0;Saved;StreamPrint("%d;",Top+Out+N-42);}|});
      Alcotest.test_case
        "PutChars initial default leaves marker for a later formal" `Quick
        (expect 42L
           {|#exe {I64 N=39;I64 Out=0;U0 PutChars(I64 a=++N,I64 b){Out=a+b;}N=0;'' 2;I64 Top=Out;U0 Saved(){'A'-63;}Out=0;Saved;StreamPrint("%d;",Top+Out+N-42);}|});
      Alcotest.test_case
        "absent Print leaves comma-separated statements in order" `Quick
        (expect 42L
           {|I64 Out=0;U0 Print(I64 a=20){Out+=a;}"",Out+=1;U0 Saved(){""(),Out+=1;}Saved;Out;|});
      Alcotest.test_case "rootless outputs preserve nested statement traversal"
        `Quick
        (expect 42L
           {|I64 Out=0;I64 i=0;U0 Print(){Out+=10;}U0 PutChars(){Out+=11;}for(i=0;i<2;""()){''();++i;}Out;|});
      Alcotest.test_case
        "implicit absent values preserve closing lookahead target" `Quick
        (expect 42L
           {|#exe {I64 Out=0;U0 Print(){Out=42;}""() #exe {U0 Print(){Out=7;}};I64 Before=Out;""();StreamPrint("%d;",Before+Out-7);}|});
      Alcotest.test_case
        "implicit empty markers select parenthesis-free defaults" `Quick
        (expect 42L
           {|I64 Out=0;U0 Print(I64 a=20,I64 b=1){Out+=a+b;}U0 PutChars(I64 a=21){Out+=a;}"";'';Out;|});
      Alcotest.test_case
        "implicit zero-parameter bodies work without parentheses" `Quick
        (expect 42L
           {|I64 Out=0;U0 Print(){Out+=10;}U0 PutChars(){Out+=11;}"";'';U0 Saved(){"";'';}Saved;Out;|});
      Alcotest.test_case
        "implicit omitted first parameter retains saved default" `Quick
        (expect 42L
           {|#exe {I64 N=39;I64 Out=0;U0 Print(I64 a=++N,I64 b){Out=a+b;}N=0;""(,2);I64 Top=Out;U0 Saved(){""(,2);}Out=0;Saved;StreamPrint("%d;",Top+Out+N-42);}|});
      Alcotest.test_case "implicit calls with no supplied values retain bodies"
        `Quick
        (expect 42L
           {|I64 Out=0;U0 Print(){Out+=10;}U0 PutChars(I64 a=11){Out+=a;}""();''();U0 Saved(){""();''();}Saved;Out;|});
      Alcotest.test_case "implicit omitted first and trailing defaults" `Quick
        (expect 42L
           {|I64 Out=0;U0 Print(I64 a=40,I64 b=2){Out=a+b;}""(,);I64 Top=Out;U0 Saved(){""(,);}Out=0;Saved;Top+Out-42;|});
      Alcotest.test_case "implicit zero parameter PutChars call" `Quick
        (expect 42L
           {|I64 Out=0;U0 PutChars(){Out+=21;}''();U0 Saved(){''();}Saved;Out;|});
      Alcotest.test_case
        "parenthesized implicit first argument overrides default" `Quick
        (expect 42L
           {|I64 Out=0;U0 Print(I64 a=7,I64 b=9){Out=a+b;}""(40,2);I64 Top=Out;U0 Saved(){""(20,22);}Out=0;Saved;Top+Out-42;|});
      Alcotest.test_case
        "parenthesized implicit target survives closing lookahead" `Quick
        (expect 42L
           {|#exe {I64 Out=0;U0 Print(U8 *s,I64 a,I64 b){Out=a+b;}""("old",40,2) #exe {U0 Print(U8 *s,I64 a=7){Out=a;}};I64 Before=Out;"new";StreamPrint("%d;",Before+Out-7);}|});
      Alcotest.test_case "parenthesized implicit variadic output" `Quick
        (fun () ->
          List.iter
            (fun mode ->
              ignore
                (Output.run ~mode {|#exe {""("%d",40+2);StreamPrint("42;");}|}
                |> Output.expect ~value:(Some 42L) "42"))
            G.modes);
      Alcotest.test_case "parenthesized implicit Print supplies fixed values"
        `Quick
        (expect 42L
           {|I64 Out=0;U0 Print(U8 *s,I64 a,I64 b){Out=a+b;}""("top",40,2);I64 Top=Out;U0 Saved(){""("body",20,22);}Out=0;Saved;Top+Out-42;|});
      Alcotest.test_case "parenthesized implicit Print overrides saved defaults"
        `Quick
        (expect 42L
           {|#exe {I64 Out=0;U0 Print(U8 *s,I64 a=7,I64 b=9){Out=a+b;}""("top",40,2);I64 Top=Out;U0 Saved(){""("body",20,22);}Out=0;Saved;StreamPrint("%d;",Top+Out-42);}|});
      Alcotest.test_case "parenthesized implicit Print keeps omitted defaults"
        `Quick
        (expect 42L
           {|#exe {I64 N=38;I64 Out=0;U0 Print(U8 *s,I64 a=++N,I64 required,I64 tail=1){Out=a+required+tail;}N=0;""("top",,2,);I64 Top=Out;U0 Saved(){""("body",,2,);}Out=0;Saved;StreamPrint("%d;",Top+Out+N-42);}|});
      Alcotest.test_case "parenthesized PutChars has supplied and default slots"
        `Quick
        (expect 42L
           {|I64 Out=0;U0 PutChars(I64 a,I64 b=2,I64 c=0){Out=a+b+c;}''(40);I64 Top=Out;U0 Saved(){''(20,22);}Out=0;Saved;Top+Out-42;|});
      Alcotest.test_case "implicit separators select saved defaults" `Quick
        (expect 42L
           {|#exe {I64 N=40;I64 Out=0;U0 Print(U8 *s,I64 a=++N,I64 b=1){Out=a+b;}N=0;"top",,;I64 Top=Out;U0 Saved(){"body",,;}Out=0;Saved;StreamPrint("%d;",Top+Out+N-42);}|});
      Alcotest.test_case "implicit defaults precede supplied required slots"
        `Quick
        (expect 42L
           {|I64 Out=0;U0 Print(U8 *s,I64 a=40,I64 b){Out=a+b;}"top",,2;I64 Top=Out;U0 Saved(){"body",,2;}Out=0;Saved;Top+Out-42;|});
      Alcotest.test_case "implicit trailing separator omits a default" `Quick
        (expect 42L
           {|I64 Out=0;U0 Print(U8 *s,I64 a=42){Out=a;}"top",;I64 Top=Out;U0 Saved(){"body",;}Out=0;Saved;Top+Out-42;|});
      Alcotest.test_case "implicit defaults are saved in directive tasks" `Quick
        (expect 42L
           {|#exe {I64 N=40;I64 Out=0;U0 Print(U8 *s,I64 n=++N){Out=n;}N=0;"saved";U0 Saved(){"saved";}Out=0;Saved;StreamPrint("%d;",Out+N+1);}|});
      Alcotest.test_case "ordinary implicit calls use closed saved defaults"
        `Quick
        (expect 42L
           {|I64 Out=0;U0 Print(U8 *s,I64 n=40+2){Out=n;}"top";U0 Saved(){"body";}Out=0;Saved;Out;|});
      Alcotest.test_case "implicit output in directive tasks" `Quick (fun () ->
          List.iter
            (fun mode ->
              ignore
                (Output.run ~mode {|#exe {"A";'B';StreamPrint("42;");}|}
                |> Output.expect ~value:(Some 42L) "AB"))
            G.modes);
      Alcotest.test_case
        "pending implicit output resumes after directive output" `Quick
        (fun () ->
          List.iter
            (fun mode ->
              ignore
                (Output.run ~mode
                   {|extern U0 Print(U8 *fmt,...);"A";#exe {'B';StreamPrint("42;");}|}
                |> Output.expect ~value:(Some 42L) "BA"))
            G.modes);
      Alcotest.test_case
        "directive implicit calls preserve selected definitions" `Quick
        (expect 42L
           {|#exe {I64 N=0;U0 Print(U8 *s){N=42;}U0 Saved(){"old";}"old" #exe {U0 Print(U8 *s){N=7;}};I64 Before=N;"new";I64 After=N;Saved;StreamPrint("%d;",Before+N-After-35);}|});
      Alcotest.test_case "replaced directive headers save each default once"
        `Quick
        (expect 42L
           {|#exe {I64 N=38;extern I64 Joined(I64 a=++N);} #exe {extern I64 Joined(I64 b=++N);} #exe {I64 Joined(I64 value=++N){return value+1;}} #exe {StreamPrint("%d;",Joined()+Joined()-N-1);}|});
      Alcotest.test_case "separate directive commands join extern headers"
        `Quick
        (expect 42L
           {|#exe {extern I64 Joined(I64 n);} #exe {I64 Joined(I64 value){return value+2;}} #exe {StreamPrint("%d;",Joined(40));}|});
      Alcotest.test_case
        "joined directive function supplies a runtime dimension" `Quick
        (expect 42L
           {|#exe {I64 N=1;extern I64 Extent();} #exe {I64 Extent(){return ++N;}} #exe {I64 A[Extent()];A[1]=40;StreamPrint("%d;",A[1]+N);}|});
      Alcotest.test_case "cross-frame integer token" `Quick
        (expect 42L {|#exe {StreamPrint("4");}2;|});
      Alcotest.test_case "generated function body" `Quick
        (expect 42L {|I64 F(){#exe {StreamPrint("return 42;");}}F();|});
      Alcotest.test_case "generated initializer operand" `Quick
        (expect 42L {|I64 G=#exe {StreamPrint("42");};G;|});
      Alcotest.test_case "nested stream buffers" `Quick
        (expect 42L {|#exe {#exe {StreamPrint("StreamPrint(\"42;\");");}}|});
      Alcotest.test_case "outer JIT task declaration" `Quick
        (expect ~modes:[ Preprocessor.Jit ] 42L
           {|I64 N=40;#exe {StreamPrint("%d;",N+2);}|});
      Alcotest.test_case "directive precedes pending statement execution" `Quick
        (expect ~modes:[ Preprocessor.Jit ] 0L
           {|I64 N=0;N=1;#exe {StreamPrint("%d;",N);}|});
      Alcotest.test_case "outer defaults retain their original result" `Quick
        (expect ~modes:[ Preprocessor.Jit ] 42L
           {|I64 N=20;I64 Next(){return ++N;};I64 Saved(I64 n=Next()){return n;};N=0;#exe {StreamPrint("%d;",Saved()+Saved());}|});
      Alcotest.test_case "activation during an outer initializer" `Quick
        (expect ~modes:[ Preprocessor.Jit ] 42L
           {|I64 N=40;I64 A[2]={++N,#exe {StreamPrint("%d",N+1);}};A[1];|});
      Alcotest.test_case "activation during a later outer default" `Quick
        (expect ~modes:[ Preprocessor.Jit ] 42L
           {|I64 N=40;I64 F(I64 a=++N,I64 b=#exe {StreamPrint("%d",N+1);}){return b;};F();|});
      Alcotest.test_case "generated declarations share outer task storage"
        `Quick
        (expect ~modes:[ Preprocessor.Jit ] 42L
           {|I64 N=40;#exe {StreamPrint("I64 Add(){return N+2;};");}Add();|});
      Alcotest.test_case "initializer effects precede pending outer stores"
        `Quick
        (expect ~modes:[ Preprocessor.Jit ] 41L
           {|I64 N=40;I64 A=++N;N=0;#exe {StreamPrint("%d;",A);}|});
    ]
