open Holyc_lib
module Cases = Stream_generation_cases
module VM = Ir_integer_interpreter

let describe errors =
  errors
  |> List.map (fun (d : Diagnostic.t) -> d.code ^ ": " ^ d.message)
  |> String.concat "; "

let run ?max_generated_bytes ?max_output_bytes ?max_output_work text =
  let session = Session.create () in
  let source =
    Session.add_source session ~path:"stream-generation.hc"
      ~contents:(Cases.headers ^ text)
  in
  let config =
    Preprocessor.Config.create ~compilation_mode:Jit ?max_generated_bytes ()
    |> Result.get_ok
  in
  run_integer_program_report ?max_output_bytes ?max_output_work session ~source
    ~config ~max_steps:100_000

let value report =
  match integer_program_report_outcome report with
  | Error errors -> Alcotest.fail (describe errors)
  | Ok result ->
      Alcotest.(check (option int64))
        "source result" (Some 42L)
        (VM.final_value result.value |> Option.map (fun word -> word.VM.bits))

let generated report =
  Option.fold ~none:0
    ~some:(fun progress -> progress.Integer_task.runtime.generated_bytes)
    (integer_program_report_progress report)

let failure code report =
  match integer_program_report_outcome report with
  | Ok _ -> Alcotest.fail ("expected " ^ code)
  | Error errors ->
      Alcotest.(check bool)
        (describe errors) true
        (List.exists (fun (d : Diagnostic.t) -> d.code = code) errors)

let values () =
  List.iter
    (fun (name, text, output, bytes) ->
      let report = run text in
      value report;
      Alcotest.(check string)
        name output
        (integer_program_report_output_bytes report);
      Alcotest.(check int) (name ^ " generated bytes") bytes (generated report))
    Cases.values

let failures () =
  List.iter
    (fun (name, text, code, output, work, bytes) ->
      let report = run text in
      failure code report;
      Alcotest.(check string)
        name output
        (integer_program_report_output_bytes report);
      Alcotest.(check int)
        (name ^ " reached work") work
        (integer_program_report_output_work report);
      Alcotest.(check int)
        (name ^ " retained generation")
        bytes (generated report))
    Cases.failures

let quotas () =
  let source = Cases.quota_source in
  value
    (run ~max_generated_bytes:3 ~max_output_bytes:2 ~max_output_work:12 source);
  let small = run ~max_generated_bytes:2 source in
  failure "HCIRVM0028" small;
  Alcotest.(check int) "failed draft did not commit" 0 (generated small);
  let work = run ~max_output_work:6 source in
  failure "HCIRVM0023" work;
  Alcotest.(check int) "work failure did not commit" 0 (generated work);
  value (run ~max_generated_bytes:6 Cases.two_streams);
  let small = run ~max_generated_bytes:5 Cases.two_streams in
  failure "HCIRVM0028" small;
  Alcotest.(check int) "previous stream remains charged" 3 (generated small)

let () =
  Alcotest.run "Original stream generation"
    [
      ( "source",
        [
          Alcotest.test_case "values and retained owners" `Quick values;
          Alcotest.test_case "reached failures" `Quick failures;
          Alcotest.test_case "shared work and cumulative bytes" `Quick quotas;
        ] );
    ]
