open Holyc_lib
module Native = Native_source_execution
module Image = X86_64_program
module Cases = Aot_source_cases

let describe errors =
  String.concat "; "
    (List.map (fun (d : Diagnostic.t) -> d.code ^ ": " ^ d.message) errors)

let checked = function
  | Ok value -> value
  | Error errors -> Alcotest.fail (describe errors)

let inputs ?max_generated_bytes text =
  let session = Session.create () in
  let source =
    Session.add_source session ~path:"native-aot-source.hc"
      ~contents:(Cases.headers ^ text)
  in
  let config =
    Preprocessor.Config.create ~compilation_mode:Aot ?max_generated_bytes ()
    |> Result.get_ok
  in
  (session, source, config)

let run ?max_steps ?max_code_bytes ?max_ir_instructions ?max_initializer_steps
    ?max_default_bytes ?max_global_bytes ?max_literal_bytes ?max_output_bytes
    ?max_output_work ?max_frame_bytes ?max_call_depth ?max_generated_bytes text
    =
  let session, source, config = inputs ?max_generated_bytes text in
  Native.evaluate
    ~max_code_bytes:(Option.value ~default:1_048_576 max_code_bytes)
    ?max_ir_instructions ?max_initializer_steps ?max_default_bytes
    ?max_global_bytes ?max_literal_bytes ?max_output_bytes ?max_output_work
    ?max_frame_bytes ?max_call_depth session ~source ~config
    ~max_steps:(Option.value ~default:100_000 max_steps)

let value report =
  let result = Native.outcome report |> checked in
  Alcotest.(check (option int64))
    "source-derived result" (Some 42L)
    (Option.map
       (fun (word : Native.word) -> word.bits)
       result.value.final_value);
  let progress = Option.get (Native.source_progress report) in
  Alcotest.(check int)
    "zero interpreted task instructions" 0 progress.runtime.executed_steps;
  let fragments = Native.fragments report in
  let modules =
    List.filter
      (fun (f : Native.fragment) -> f.kind = Native.Aot_module)
      fragments
  in
  Alcotest.(check int) "one distinct original module" 1 (List.length modules);
  Alcotest.(check bool)
    "module follows directive fragments" true
    ((List.hd (List.rev fragments)).kind = Native.Aot_module);
  List.iter
    (fun (f : Native.fragment) ->
      match f.native_outcome with
      | Some (Ok (Image.Completed _)) -> ()
      | _ -> Alcotest.fail "fragment has no actual native completion")
    fragments

let failure ?code report =
  match Native.outcome report with
  | Ok _ -> Alcotest.fail "expected failure"
  | Error errors ->
      Alcotest.(check bool) "structured failure" true (errors <> []);
      Option.iter
        (fun code ->
          Alcotest.(check bool)
            (describe errors) true
            (List.exists (fun (d : Diagnostic.t) -> d.code = code) errors))
        code

let values () =
  List.iter
    (fun (name, text, output, generated) ->
      let report = run text in
      value report;
      Alcotest.(check string) name output (Native.output_bytes report);
      Alcotest.(check int)
        (name ^ " generated bytes")
        generated
        (Option.get (Native.source_progress report)).runtime.generated_bytes;
      let session, source, config = inputs text in
      let ir =
        run_integer_program_report session ~source ~config ~max_steps:100_000
      in
      let result = integer_program_report_outcome ir |> checked in
      Alcotest.(check (option int64))
        (name ^ " fresh IR result")
        (Some 42L)
        (Option.map
           (fun (word : Ir_integer_interpreter.word) -> word.bits)
           (Ir_integer_interpreter.final_value result.value));
      Alcotest.(check string)
        (name ^ " fresh IR output")
        output
        (integer_program_report_output_bytes ir);
      Alcotest.(check int)
        (name ^ " original formatting work")
        (integer_program_report_output_work ir)
        (Native.output_work report))
    Cases.successes

let source =
  {|I64 F(I64 n=40){return n;}#exe {I64 G(I64 n=2){return n;}Print("parse;");StreamPrint("I64 N=%d;",G);}Print("load;");F+N;|}

let cumulative_limits () =
  let baseline = run source in
  value baseline;
  let steps = Native.executed_steps baseline in
  value (run ~max_steps:steps source);
  let stopped = run ~max_steps:(steps - 1) source in
  failure ~code:"HCIRVM0007" stopped;
  Alcotest.(check int)
    "cumulative attempted instructions" (steps - 1)
    (Native.executed_steps stopped);
  let work = Native.preparation_steps baseline in
  value (run ~max_initializer_steps:work source);
  failure (run ~max_initializer_steps:(work - 1) source);
  value (run ~max_default_bytes:16 source);
  let defaults = run ~max_default_bytes:15 source in
  failure ~code:"HCIRVM0011" defaults;
  Alcotest.(check bool)
    "exhausted defaults prevent module entry" false
    (List.exists
       (fun (f : Native.fragment) -> f.kind = Native.Aot_module)
       (Native.fragments defaults));
  let code, ir =
    List.fold_left
      (fun (code, ir) (f : Native.fragment) ->
        (code + f.image.code_bytes, ir + f.image.ir_instructions))
      (0, 0)
      (Native.fragments baseline)
  in
  value (run ~max_code_bytes:code ~max_ir_instructions:ir source);
  failure ~code:"HCBACK0005" (run ~max_code_bytes:(code - 1) source);
  failure ~code:"HCBACK0001" (run ~max_ir_instructions:(ir - 1) source);
  value (run ~max_generated_bytes:8 source);
  failure ~code:"HCIRVM0028" (run ~max_generated_bytes:7 source);
  let output = Native.output_bytes baseline
  and output_work = Native.output_work baseline in
  value
    (run ~max_output_bytes:(String.length output) ~max_output_work:output_work
       source);
  failure ~code:"HCIRVM0022"
    (run ~max_output_bytes:(String.length output - 1) source);
  failure ~code:"HCIRVM0023" (run ~max_output_work:(output_work - 1) source)

let storage_limits () =
  let text = {|I64 A=40;#exe {I64 A=1;StreamPrint("I64 N=2;");}A+N;|} in
  let baseline = run text in
  value baseline;
  value (run ~max_global_bytes:24 text);
  let stopped = run ~max_global_bytes:23 text in
  failure ~code:"HCBACK0004" stopped;
  Alcotest.(check bool)
    "no module after storage rejection" false
    (List.exists
       (fun (f : Native.fragment) -> f.kind = Native.Aot_module)
       (Native.fragments stopped));
  let text = {|#exe {Print("parse;");StreamPrint("Print(\"load;\");42;");}|} in
  let baseline = run text in
  value baseline;
  let literals =
    List.fold_left
      (fun total (f : Native.fragment) ->
        if f.kind = Native.Aot_module then total + f.image.literal_bytes
        else max total f.image.literal_bytes)
      0
      (Native.fragments baseline)
  in
  value (run ~max_literal_bytes:literals text);
  failure ~code:"HCBACK0004" (run ~max_literal_bytes:(literals - 1) text)

let failure_order () =
  let module_fault = run {|#exe {Print("parse;");}Print("load;");1/0;|} in
  failure ~code:"HCIRVM0009" module_fault;
  Alcotest.(check string)
    "both reached stages retained" "parse;load;"
    (Native.output_bytes module_fault);
  let module_ = List.hd (List.rev (Native.fragments module_fault)) in
  (match module_.native_outcome with
  | Some (Ok (Image.Fault _)) ->
      Alcotest.(check bool)
        "fault belongs to module" true
        (module_.kind = Native.Aot_module)
  | _ -> Alcotest.fail "module fault lacks machine evidence");
  let task_fault = run {|#exe {Print("keep;");I64 N;N;}42;|} in
  failure ~code:"HCIRVM0012" task_fault;
  Alcotest.(check string)
    "task output survives reached fault" "keep;"
    (Native.output_bytes task_fault);
  Alcotest.(check bool)
    "module never entered" false
    (List.exists
       (fun (f : Native.fragment) -> f.kind = Native.Aot_module)
       (Native.fragments task_fault));
  let malformed =
    run {|#exe {Print("keep;");StreamPrint("I64 Broken=;");}42;|}
  in
  failure malformed;
  Alcotest.(check string)
    "output survives generated parse failure" "keep;"
    (Native.output_bytes malformed);
  Alcotest.(check int)
    "committed generated bytes remain charged"
    (String.length "I64 Broken=;")
    (Option.get (Native.source_progress malformed)).runtime.generated_bytes;
  failure (run {|I64 Outer=40;#exe {StreamPrint("%d;",Outer+2);}|});
  failure (run {|I64 F(I64 n=40){#exe {StreamPrint("%d;",n+2);}return 0;}F;|});
  let synchronous = run {|#exe {StreamExePrint("42;");}42;|} in
  value synchronous

let () =
  Alcotest.run "Native AOT source sessions"
    [
      ( "original source",
        [
          Alcotest.test_case "values, namespaces, retained tasks and output"
            `Quick values;
          Alcotest.test_case "shared work and code boundaries" `Quick
            cumulative_limits;
          Alcotest.test_case "combined storage bounds" `Quick storage_limits;
          Alcotest.test_case "reached failures and dependencies" `Quick
            failure_order;
        ] );
    ]
