type t
type command
type stream

(** Incremental JIT execution with retained globals and functions. Calls
    preserve each body's original storage, literals and callees. [run] retains
    assigned declaration symbols across parsing and compilation; partial runtime
    publication and #exe integration remain separate work. *)

val create :
  ?max_steps:int ->
  ?max_initializer_steps:int ->
  ?max_global_bytes:int ->
  ?max_literal_bytes:int ->
  ?max_frame_bytes:int ->
  ?max_call_depth:int ->
  ?max_output_bytes:int ->
  ?max_output_work:int ->
  ?max_generated_bytes:int ->
  ?max_stream_depth:int ->
  Session.t ->
  (t, string) result
(** Limits belong to the task. Preparation is charged during compilation,
    including reached failures; runtime instructions, allocations and ordinary
    output are cumulative across admitted commands. Frame bytes and call depth
    bound simultaneously active calls. *)

val output_bytes : t -> string
val output_work : t -> int
val generated_bytes : t -> int
val executed_steps : t -> int
val initializer_steps : t -> int
val begin_stream : t -> (stream, string) result
val finish_stream : t -> stream -> (string, string) result

val abort_stream : t -> stream -> (unit, string) result
(** Opaque LIFO generation buffers for the parser executor. StreamPrint needs a
    checked extern header and an active buffer. It shares ordinary formatting
    work; generated bytes have a separate cumulative bound (default 16 MiB).
    Active depth defaults to 64. Finish returns that buffer's text; abort
    returns none. Reached work and generated bytes remain charged on both paths.
*)

val compile_ast :
  t -> Frontend.Ast.module_ -> (command, Common.Diagnostic.t list) result
(** Compile only this syntax through the ordinary pipeline. Reusing the same
    parsed command returns its existing receipt; overlapping command items are
    rejected. Pending commands retain earlier bindings across later shadow
    publications. Parser-aware predecessor authority remains separate work. *)

val execute :
  t -> command -> (Ir.Integer_interpreter.t, Common.Diagnostic.t list) result
(** Preflight before admitting storage or consuming the receipt. Success and
    reached faults consume it; earlier writes survive a reached fault. Foreign
    commands and replay report HCIRVM0026 without effects. *)

val run :
  t ->
  source:Common.Source_file.t ->
  (Ir.Integer_interpreter.t, Common.Diagnostic.t list) result
(** Parse the exact registered source with declaration observation, then compile
    using those assigned symbols in the task's shared module scope. Reached
    semantic publications survive parse errors; failed declarations have no
    runtime binding. [compile_ast] retains its callback-free collection path. *)
