type output = {
  ast : Ast.module_ option;
  diagnostics : Common.Diagnostic.t list;
}

val max_pointer_depth : int
val max_expression_depth : int
val max_block_depth : int
val max_conditional_depth : int
val max_loop_depth : int
val max_lock_depth : int
val max_try_depth : int
val max_switch_depth : int
val max_aggregate_depth : int
val max_initializer_depth : int

type reference_selection

val selected_identifier : reference_selection -> Ast.identifier

val selected_environment :
  reference_selection -> Symbol_visibility.Environment.t

val selected_lookup : reference_selection -> Symbol_visibility.lookup
(** Selection frozen when the identifier token was produced, before later
    lookahead can execute a directive. The receipt belongs to this exact AST
    occurrence and environment. Selected absence and local shadowing also remain
    fixed. Retain entry objects, not environment-local numeric IDs. *)

type command_sink = {
  reference :
    (reference_selection -> (unit, Common.Diagnostic.t list) result) option;
  command : Ast.item -> (unit, Common.Diagnostic.t list) result;
  resume : unit -> (unit, Common.Diagnostic.t list) result;
}
(** [command] receives a completed syntax command. [resume] runs after the next
    command's initial lookahead, including any #exe reached during that
    lookahead. The sink owns pending execution and must tolerate [resume] with
    no pending command. A reported error stops further command delivery. *)

type stream_execution = {
  definitions : Definition.Environment.t;
  symbols : Symbol_visibility.Environment.t;
  commands : command_sink;
  finish : unit -> (string, Common.Diagnostic.t list) result;
  abort : unit -> unit;
}
(** One active generation buffer and its task environment. The parser consumes
    ordinary command grammar in temporary JIT mode with no outer function-local
    context. [finish] supplies generated bytes only after a closing brace and
    successful commands. [abort] releases the buffer on any earlier failure,
    including an exception. Successful generation is inserted at the current
    lexer position after restoring the outer environment. *)

val parse :
  ?commands:command_sink ->
  ?execute_stream:
    (Common.Span.t -> (stream_execution, Common.Diagnostic.t list) result) ->
  sources:Common.Source_manager.t ->
  definitions:Definition.Environment.t ->
  symbols:Symbol_visibility.Environment.t ->
  config:Preprocessor.Config.t ->
  Common.Source_file.t ->
  output

val has_errors : output -> bool
