type output = {
  ast : Ast.module_ option;
  diagnostics : Common.Diagnostic.t list;
}

val max_pointer_depth : int
val max_expression_depth : int
val max_block_depth : int
val max_conditional_depth : int
val max_loop_depth : int
val max_lock_depth : int
val max_try_depth : int
val max_switch_depth : int
val max_aggregate_depth : int
val max_initializer_depth : int

type reference_selection

val selected_identifier : reference_selection -> Ast.identifier

val selected_environment :
  reference_selection -> Symbol_visibility.Environment.t

val selected_lookup : reference_selection -> Symbol_visibility.lookup
(** Selection captured when the identifier token was produced, before later
    lookahead can execute a directive. Header completion promotes an unconsumed
    buffered token selecting that exact provisional function. Once delivered,
    the receipt remains fixed and belongs to this exact AST occurrence and
    environment. Selected absence and local shadowing also remain fixed. Retain
    entry objects, not environment-local numeric IDs. *)

type declaration_header = private {
  declaration_sources : Common.Source_manager.t;
  declaration_source : Common.Source_file.t;
  modifiers : Ast.declaration_modifier list;
  binding : Ast.declaration_binding option;
  type_specifier : Ast.type_specifier;
}

type global_publication = private {
  global_header : declaration_header;
  global_environment : Symbol_visibility.Environment.t;
  global_entry : Symbol_visibility.entry;
  global_previous : Symbol_visibility.lookup;
  global_name : Ast.identifier;
  global_pointer_layers : Ast.pointer_layer list;
  global_function_pointer : Ast.function_pointer_declarator option;
  global_dimensions : Ast.array_dimension list;
}

type function_publication = private {
  function_header : declaration_header;
  function_environment : Symbol_visibility.Environment.t;
  function_entry : Symbol_visibility.entry;
  function_previous : Symbol_visibility.lookup;
  function_name : Ast.identifier;
  function_pointer_layers : Ast.pointer_layer list;
  function_opening_parenthesis : Ast.location;
}

type completed_function_header = private {
  function_publication : function_publication;
  completed_entry : Symbol_visibility.entry;
  parameters : Ast.function_parameter list;
  empty_parameter_entries : Ast.empty_parameter_entry list;
  variadic : Ast.variadic_marker option;
  closing_parenthesis : Ast.location;
}

type declaration_event = private
  | Global_declared of global_publication
  | Global_completed of global_publication * Ast.global_declarator
  | Function_declared of function_publication
  | Function_header_completed of completed_function_header
  | Function_body_completed of
      completed_function_header * Ast.function_definition
      (** Parser-owned source witnesses. A global is declared after its
          dimensions, before its initializer; completion precedes lookahead past
          its delimiter. A function is provisional before parameter parsing.
          Header completion follows the first lookahead past ')'; body
          completion follows body parsing and its terminating lookahead,
          including a native empty body at EOF. Completion records reuse exact
          source nodes and their declaration witness. Runtime validation,
          installation and replay admission remain the consumer's work. *)

type command_sink = {
  reference :
    (reference_selection -> (unit, Common.Diagnostic.t list) result) option;
  declaration :
    (declaration_event -> (unit, Common.Diagnostic.t list) result) option;
  command : Ast.item -> (unit, Common.Diagnostic.t list) result;
  resume : unit -> (unit, Common.Diagnostic.t list) result;
}
(** [command] receives a completed syntax command. [resume] runs after the next
    command's initial lookahead, including any #exe reached during that
    lookahead. The sink owns pending execution and must tolerate [resume] with
    no pending command. A reported error stops further command delivery. *)

type stream_execution = {
  definitions : Definition.Environment.t;
  symbols : Symbol_visibility.Environment.t;
  commands : command_sink;
  finish : unit -> (string, Common.Diagnostic.t list) result;
  abort : unit -> unit;
}
(** One active generation buffer and its task environment. The parser consumes
    ordinary command grammar in temporary JIT mode with no outer function-local
    context. [finish] supplies generated bytes only after a closing brace and
    successful commands. [abort] releases the buffer on any earlier failure,
    including an exception. Successful generation is inserted at the current
    lexer position after restoring the outer environment. *)

val parse :
  ?commands:command_sink ->
  ?execute_stream:
    (Common.Span.t -> (stream_execution, Common.Diagnostic.t list) result) ->
  sources:Common.Source_manager.t ->
  definitions:Definition.Environment.t ->
  symbols:Symbol_visibility.Environment.t ->
  config:Preprocessor.Config.t ->
  Common.Source_file.t ->
  output

val has_errors : output -> bool
