type compilation_mode = Jit | Aot

let compilation_mode_name = function
  | Jit -> "jit"
  | Aot -> "aot"

module Config = struct
  type t = {
    resolver : Include_resolver.t;
    compilation_mode : compilation_mode;
    max_conditional_depth : int;
    max_include_depth : int;
    max_source_bytes : int;
    max_definition_depth : int;
    max_generated_bytes : int;
    max_expression_nodes : int;
    predefined : Predefined.Settings.t;
  }

  let create ?working_directory ?include_roots ?templeos_root
      ?(compilation_mode = Jit) ?(max_conditional_depth = 64)
      ?(max_include_depth = 64) ?(max_source_bytes = 64 * 1024 * 1024)
      ?(max_definition_depth = 64) ?(max_generated_bytes = 16 * 1024 * 1024)
      ?(max_expression_nodes = 512) ?predefined_date ?predefined_time
      ?(command_line_source = false) () =
    if max_conditional_depth < 0 then
      Error "conditional depth limit must be nonnegative"
    else if max_include_depth < 0 then
      Error "include depth limit must be nonnegative"
    else if max_source_bytes < 0 then
      Error "included source size limit must be nonnegative"
    else if max_definition_depth < 0 then
      Error "definition depth limit must be nonnegative"
    else if max_generated_bytes < 0 then
      Error "generated byte limit must be nonnegative"
    else if max_expression_nodes < 0 then
      Error "conditional expression node limit must be nonnegative"
    else
      match
        Predefined.Settings.create ?date:predefined_date ?time:predefined_time
          ~command_line:command_line_source ()
      with
      | Error _ as error -> error
      | Ok predefined -> (
          match
            Include_resolver.create ?working_directory ?include_roots
              ?templeos_root ()
          with
          | Error _ as error -> error
          | Ok resolver ->
              Ok
                {
                  resolver;
                  compilation_mode;
                  max_conditional_depth;
                  max_include_depth;
                  max_source_bytes;
                  max_definition_depth;
                  max_generated_bytes;
                  max_expression_nodes;
                  predefined;
                })

  let resolver config = config.resolver
  let compilation_mode config = config.compilation_mode
  let max_conditional_depth config = config.max_conditional_depth
  let max_include_depth config = config.max_include_depth
  let max_source_bytes config = config.max_source_bytes
  let max_definition_depth config = config.max_definition_depth
  let max_generated_bytes config = config.max_generated_bytes
  let max_expression_nodes config = config.max_expression_nodes
  let predefined config = config.predefined
end

type conditional_branch = Then_branch | Else_branch

type conditional = {
  keyword : Keyword.t;
  opener : Common.Span.t;
  parent_active : bool;
  condition : bool;
  mutable branch : conditional_branch;
  mutable valid : bool;
  include_stack : Common.Diagnostic.related list;
  definition_trace : Common.Diagnostic.related list;
}

type t = {
  sources : Common.Source_manager.t;
  definitions : Definition.Environment.t;
  symbols : Symbol_visibility.Environment.t;
  config : Config.t;
  mutable current : Lexer_frame.t;
  mutable lookahead : Token.t option;
  mutable generated_bytes : int;
  mutable conditionals : conditional list;
  mutable conditional_poisoned : bool;
  mutable pending_diagnostics : Common.Diagnostic.t list;
  mutable help_metadata : Help_metadata.t;
}

type diagnostic_context = {
  include_stack : Common.Diagnostic.related list;
  definition_trace : Common.Diagnostic.related list;
}

type output = {
  tokens : Token.t list;
  diagnostics : Common.Diagnostic.t list;
  help_metadata : Help_metadata.t;
}

let create ~sources ~definitions ~symbols ~config source =
  {
    sources;
    definitions;
    symbols;
    config;
    current = Lexer_frame.root ~mode:Token.Holyc source;
    lookahead = None;
    generated_bytes = 0;
    conditionals = [];
    conditional_poisoned = false;
    pending_diagnostics = [];
    help_metadata = Help_metadata.empty;
  }

let rec discard_exhausted_frames stream =
  if Lexer.local_at_end (Lexer_frame.lexer stream.current) then
    match Lexer_frame.caller stream.current with
    | None -> ()
    | Some caller ->
        stream.current <- caller;
        discard_exhausted_frames stream

let rec align_current_to_source stream source =
  if Common.Source_id.equal (Lexer_frame.source_id stream.current) source then
    ()
  else
    match Lexer_frame.caller stream.current with
    | None ->
        invalid_arg
          "preprocessor lexer item does not belong to the active source frame \
           chain"
    | Some caller ->
        stream.current <- caller;
        align_current_to_source stream source

let next_lexer_item stream =
  discard_exhausted_frames stream;
  let item = Lexer.next (Lexer_frame.lexer stream.current) in
  let source =
    match item with
    | Lexer.Token token -> token.Token.span.source
    | Lexer.Diagnostic diagnostic -> diagnostic.Common.Diagnostic.primary.source
  in
  align_current_to_source stream source;
  item

let zero_span source =
  Common.Span.unsafe_make
    ~source:(Common.Source_file.id source)
    ~start:0 ~stop:0

let current_diagnostic_context stream =
  {
    include_stack = Lexer_frame.include_stack stream.current;
    definition_trace = Lexer_frame.definition_trace stream.current;
  }

let diagnostic_context stream = current_diagnostic_context stream

let same_related (left : Common.Diagnostic.related)
    (right : Common.Diagnostic.related) =
  Common.Span.compare left.span right.span = 0
  && String.equal left.message right.message

let append_distinct_related existing additions =
  List.fold_left
    (fun items item ->
      if List.exists (same_related item) items then items else items @ [ item ])
    existing additions

let merge_diagnostic_context left right =
  {
    include_stack =
      append_distinct_related left.include_stack right.include_stack;
    definition_trace =
      append_distinct_related left.definition_trace right.definition_trace;
  }

let diagnostic stream ?context ?(secondary = []) ?(notes = []) ?help ~code
    ?(severity = Common.Diagnostic.Error) ~message primary =
  let context =
    Option.value context ~default:(current_diagnostic_context stream)
  in
  let secondary = secondary @ context.definition_trace in
  Common.Diagnostic.make ~secondary ~include_stack:context.include_stack ~notes
    ?help ~code ~severity ~message ~primary ()

let decorate_lexer_diagnostic stream (item : Common.Diagnostic.t) =
  {
    item with
    Common.Diagnostic.include_stack = Lexer_frame.include_stack stream.current;
    secondary = item.secondary @ Lexer_frame.definition_trace stream.current;
  }

let current_active stream =
  if stream.conditional_poisoned then false
  else
    match stream.conditionals with
    | [] -> true
    | conditional :: _ -> (
        conditional.valid && conditional.parent_active
        &&
        match conditional.branch with
        | Then_branch -> conditional.condition
        | Else_branch -> not conditional.condition)

let directive_span hash token =
  if Common.Source_id.equal hash.Token.span.source token.Token.span.source then
    Common.Span.unsafe_make ~source:hash.Token.span.source
      ~start:hash.Token.span.start ~stop:token.Token.span.stop
  else token.Token.span

let push_conditional ?parent_active ?(valid = true) stream hash token keyword
    condition =
  let limit = Config.max_conditional_depth stream.config in
  if List.length stream.conditionals >= limit then (
    stream.conditionals <- [];
    stream.conditional_poisoned <- true;
    Error
      (diagnostic stream ~code:"HCPP0019"
         ~message:
           (Printf.sprintf "#%s would exceed the conditional depth limit of %d"
              (Keyword.spelling keyword) limit)
         ~help:"Raise the conditional depth limit only for trusted source."
         token.Token.span))
  else
    let parent_active =
      Option.value parent_active ~default:(current_active stream)
    in
    let conditional =
      {
        keyword;
        opener = directive_span hash token;
        parent_active;
        condition;
        branch = Then_branch;
        valid;
        include_stack = Lexer_frame.include_stack stream.current;
        definition_trace = Lexer_frame.definition_trace stream.current;
      }
    in
    stream.conditionals <- conditional :: stream.conditionals;
    Ok ()

let opener_related conditional : Common.Diagnostic.related =
  {
    span = conditional.opener;
    message =
      Printf.sprintf "the #%s conditional starts here"
        (Keyword.spelling conditional.keyword);
  }

let conditional_else stream token =
  match stream.conditionals with
  | [] ->
      Error
        (diagnostic stream ~code:"HCPP0015"
           ~message:"found #else without an active conditional"
           ~help:"Remove #else or add its opening conditional." token.Token.span)
  | conditional :: _ -> (
      match conditional.branch with
      | Then_branch ->
          conditional.branch <- Else_branch;
          Ok ()
      | Else_branch ->
          conditional.valid <- false;
          Error
            (diagnostic stream
               ~secondary:[ opener_related conditional ]
               ~code:"HCPP0016" ~message:"this conditional already has an #else"
               ~help:"Keep one #else branch for each conditional."
               token.Token.span))

let conditional_endif stream token =
  match stream.conditionals with
  | [] ->
      Error
        (diagnostic stream ~code:"HCPP0017"
           ~message:"found #endif without an active conditional"
           ~help:"Remove #endif or add its opening conditional."
           token.Token.span)
  | _ :: rest ->
      stream.conditionals <- rest;
      Ok ()

let unterminated_conditional (conditional : conditional) =
  Common.Diagnostic.make ~secondary:conditional.definition_trace
    ~include_stack:conditional.include_stack ~code:"HCPP0018"
    ~severity:Common.Diagnostic.Error
    ~message:
      (Printf.sprintf "#%s has no matching #endif"
         (Keyword.spelling conditional.keyword))
    ~primary:conditional.opener
    ~help:"Add #endif before the end of the preprocessing stream." ()

let finish_conditionals stream =
  match List.rev stream.conditionals with
  | [] -> None
  | first :: rest ->
      stream.conditionals <- [];
      stream.pending_diagnostics <-
        List.map unterminated_conditional rest @ stream.pending_diagnostics;
      Some (unterminated_conditional first)

let token_text token =
  match token.Token.value with
  | Token.Text text | Token.Bytes text -> Some text
  | Token.No_value | Token.Int64 _ | Token.Float64 _ -> None

let path_problem stream primary = function
  | Include_resolver.Empty_path ->
      diagnostic stream ~code:"HCPP0002"
        ~message:"the #include path cannot be empty" primary
  | Include_resolver.Path_contains_nul ->
      diagnostic stream ~code:"HCPP0002"
        ~message:"the #include path contains a NUL byte" primary
  | Include_resolver.Not_found { spelling; searched } ->
      let notes = List.map (Printf.sprintf "searched %s") searched in
      diagnostic stream ~notes ~code:"HCPP0003"
        ~message:(Printf.sprintf "could not find included source %S" spelling)
        primary
  | Include_resolver.Outside_allowed_roots { spelling; resolved; allowed_roots }
    ->
      let notes =
        Printf.sprintf "resolved path: %s" resolved
        :: List.map (Printf.sprintf "allowed root: %s") allowed_roots
      in
      diagnostic stream ~notes ~code:"HCPP0004"
        ~message:
          (Printf.sprintf "included source %S is outside the allowed roots"
             spelling)
        ~help:
          "Add the containing directory as an include root only if the source \
           is trusted."
        primary
  | Include_resolver.Is_directory path ->
      diagnostic stream ~code:"HCPP0007"
        ~message:(Printf.sprintf "included path is a directory: %s" path)
        primary
  | Include_resolver.Not_regular_file path ->
      diagnostic stream ~code:"HCPP0007"
        ~message:(Printf.sprintf "included path is not a regular file: %s" path)
        primary
  | Include_resolver.Io_error { path; message } ->
      diagnostic stream
        ~notes:[ Printf.sprintf "host error: %s" message ]
        ~code:"HCPP0007"
        ~message:(Printf.sprintf "could not inspect included source %s" path)
        primary
  | Include_resolver.Home_path_requires_mapping spelling ->
      diagnostic stream ~code:"HCPP0009"
        ~message:
          (Printf.sprintf
             "TempleOS home path %S has no hosted directory mapping" spelling)
        ~help:"Use a configured include root and a relative include path."
        primary
  | Include_resolver.Templeos_root_requires_mapping spelling ->
      diagnostic stream ~code:"HCPP0009"
        ~message:
          (Printf.sprintf "TempleOS root path %S requires --templeos-root"
             spelling)
        primary
  | Include_resolver.Drive_path_unsupported spelling ->
      diagnostic stream ~code:"HCPP0009"
        ~message:
          (Printf.sprintf "TempleOS drive path %S is not supported on this host"
             spelling)
        ~help:"Map the source tree with --templeos-root and use a root path."
        primary

let help_path_problem stream primary = function
  | Include_resolver.Empty_path ->
      diagnostic stream ~code:"HCPP0030"
        ~message:"the #help_file path cannot be empty" primary
  | Include_resolver.Path_contains_nul ->
      diagnostic stream ~code:"HCPP0030"
        ~message:"the #help_file path contains a NUL byte" primary
  | Include_resolver.Outside_allowed_roots { spelling; resolved; allowed_roots }
    ->
      let notes =
        Printf.sprintf "resolved path: %s" resolved
        :: List.map (Printf.sprintf "allowed root: %s") allowed_roots
      in
      diagnostic stream ~notes ~code:"HCPP0004"
        ~message:
          (Printf.sprintf "help file %S is outside the allowed roots" spelling)
        ~help:
          "Add the containing directory as an allowed root only if the source \
           is trusted."
        primary
  | Include_resolver.Home_path_requires_mapping spelling ->
      diagnostic stream ~code:"HCPP0009"
        ~message:
          (Printf.sprintf
             "TempleOS home path %S has no hosted directory mapping" spelling)
        primary
  | Include_resolver.Templeos_root_requires_mapping spelling ->
      diagnostic stream ~code:"HCPP0009"
        ~message:
          (Printf.sprintf "TempleOS help path %S requires --templeos-root"
             spelling)
        primary
  | Include_resolver.Drive_path_unsupported spelling ->
      diagnostic stream ~code:"HCPP0009"
        ~message:
          (Printf.sprintf "TempleOS drive path %S is not supported on this host"
             spelling)
        primary
  | Include_resolver.Not_found { spelling; searched } ->
      diagnostic stream
        ~notes:(List.map (Printf.sprintf "considered %s") searched)
        ~code:"HCPP0030"
        ~message:(Printf.sprintf "could not resolve help file %S" spelling)
        primary
  | Include_resolver.Is_directory path ->
      diagnostic stream ~code:"HCPP0030"
        ~message:(Printf.sprintf "help path is a directory: %s" path)
        primary
  | Include_resolver.Not_regular_file path ->
      diagnostic stream ~code:"HCPP0030"
        ~message:(Printf.sprintf "help path is not a regular file: %s" path)
        primary
  | Include_resolver.Io_error { path; message } ->
      diagnostic stream
        ~notes:[ Printf.sprintf "host error: %s" message ]
        ~code:"HCPP0030"
        ~message:(Printf.sprintf "could not resolve help path %s" path)
        primary

let cycle_diagnostic stream ~spelling ~canonical_path ~primary active =
  let active_span =
    match Lexer_frame.include_origin active with
    | Some span -> span
    | None -> zero_span (Lexer_frame.source active)
  in
  let related : Common.Diagnostic.related =
    {
      span = active_span;
      message = "this source is already active in the include stack";
    }
  in
  diagnostic stream ~secondary:[ related ]
    ~notes:[ Printf.sprintf "canonical path: %s" canonical_path ]
    ~code:"HCPP0005"
    ~message:(Printf.sprintf "including %S would create a cycle" spelling)
    primary

let depth_diagnostic stream ~spelling ~primary =
  let limit = Config.max_include_depth stream.config in
  diagnostic stream ~code:"HCPP0006"
    ~message:
      (Printf.sprintf "including %S would exceed the include depth limit of %d"
         spelling limit)
    ~help:"Raise the include depth limit only for a trusted source tree."
    primary

let load_diagnostic stream ~spelling ~path ~primary message =
  diagnostic stream
    ~notes:[ Printf.sprintf "host error: %s" message ]
    ~code:"HCPP0007"
    ~message:
      (Printf.sprintf "could not read included source %S at %s" spelling path)
    primary

let push_include stream token spelling =
  let next_depth = Lexer_frame.source_depth stream.current + 1 in
  if next_depth >= Config.max_include_depth stream.config then
    Error (depth_diagnostic stream ~spelling ~primary:token.Token.span)
  else
    match
      Include_resolver.resolve (Config.resolver stream.config) ~spelling
    with
    | Error problem -> Error (path_problem stream token.span problem)
    | Ok resolution -> (
        match
          Lexer_frame.find_active_path stream.current resolution.canonical_path
        with
        | Some active ->
            Error
              (cycle_diagnostic stream ~spelling
                 ~canonical_path:resolution.canonical_path ~primary:token.span
                 active)
        | None -> (
            match
              Common.Source_manager.load
                ~max_bytes:(Config.max_source_bytes stream.config)
                ~display_path:spelling stream.sources
                ~path:resolution.canonical_path
            with
            | Error message ->
                Error
                  (load_diagnostic stream ~spelling
                     ~path:resolution.canonical_path ~primary:token.span message)
            | Ok source ->
                stream.current <-
                  Lexer_frame.push_include ~caller:stream.current ~source
                    ~include_origin:token.span ~include_spelling:spelling;
                Ok ()))

let expected_directive stream token =
  diagnostic stream ~code:"HCPP0001"
    ~message:"expected a preprocessor directive name after #" token.Token.span

let unsupported_directive stream token keyword =
  let spelling = Keyword.spelling keyword in
  diagnostic stream ~code:"HCPP0008"
    ~message:
      (Printf.sprintf
         "#%s is not implemented by the preprocessed token stream yet" spelling)
    token.Token.span

let definition_name token =
  match token.Token.kind with
  | Token_kind.Identifier | Token_kind.Keyword _ -> token_text token
  | _ -> None

let invalid_definition_name stream token =
  diagnostic stream ~code:"HCPP0010"
    ~message:"expected a definition name after #define" token.Token.span

let invalid_symbol_condition_name stream token keyword =
  diagnostic stream ~code:"HCPP0020"
    ~message:
      (Printf.sprintf "expected a symbol name after #%s"
         (Keyword.spelling keyword))
    token.Token.span

let next_unexpanded stream =
  match next_lexer_item stream with
  | Lexer.Diagnostic item ->
      let item = decorate_lexer_diagnostic stream item in
      Lexer.Diagnostic item
  | Lexer.Token token when token.Token.kind = Token_kind.Eof ->
      Lexer.Token token
  | item -> item

let define stream hash =
  match next_unexpanded stream with
  | Lexer.Diagnostic item -> Error item
  | Lexer.Token name_token -> (
      match definition_name name_token with
      | None -> Error (invalid_definition_name stream name_token)
      | Some name -> (
          let lexer = Lexer_frame.lexer stream.current in
          let capture = Lexer.capture_definition_replacement lexer in
          let same_source =
            Common.Source_id.equal hash.Token.span.source name_token.span.source
          in
          let definition_span =
            Common.Span.unsafe_make ~source:name_token.Token.span.source
              ~start:
                (if same_source then hash.Token.span.start
                 else name_token.Token.span.start)
              ~stop:(Lexer.offset lexer)
          in
          match capture.terminator with
          | Lexer.Nul ->
              Error
                (diagnostic stream ~code:"HCPP0014"
                   ~message:"a NUL byte ended the #define replacement"
                   capture.replacement_span)
          | Lexer.End_of_line | Lexer.End_of_file ->
              ignore
                (Definition.Environment.define stream.definitions ~name
                   ~replacement:capture.replacement ~name_span:name_token.span
                   ~definition_span ~replacement_span:capture.replacement_span
                   ~segments:capture.segments);
              Ok ()))

let definition_cycle stream definition invocation =
  diagnostic stream ~code:"HCPP0011"
    ~message:
      (Printf.sprintf "definition %S expands recursively"
         (Definition.name definition))
    ~help:"Change the definition so its active expansion cannot reach itself."
    invocation

type expansion_origin =
  | Text_definition of Definition.t
  | Compiler_predefined of Predefined.t

let expansion_description = function
  | Text_definition definition ->
      Printf.sprintf "definition %S" (Definition.name definition)
  | Compiler_predefined predefined ->
      Printf.sprintf "predefined value %S" (Predefined.spelling predefined)

let definition_depth stream origin invocation =
  diagnostic stream ~code:"HCPP0012"
    ~message:
      (Printf.sprintf
         "expanding %s would exceed the definition depth limit of %d"
         (expansion_description origin)
         (Config.max_definition_depth stream.config))
    ~help:"Raise the definition depth limit only for trusted source." invocation

let generated_bytes stream origin replacement_bytes invocation =
  diagnostic stream ~code:"HCPP0013"
    ~message:
      (Printf.sprintf "expanding %s would exceed the generated byte limit of %d"
         (expansion_description origin)
         (Config.max_generated_bytes stream.config))
    ~notes:
      [
        Printf.sprintf "bytes already injected: %d" stream.generated_bytes;
        Printf.sprintf "replacement bytes: %d" replacement_bytes;
      ]
    ~help:"Raise the generated byte limit only for trusted source." invocation

let push_replacement stream token origin replacement =
  let next_depth = Lexer_frame.definition_depth stream.current + 1 in
  if next_depth > Config.max_definition_depth stream.config then
    Error (definition_depth stream origin token.Token.span)
  else
    let replacement_bytes = String.length replacement in
    let byte_limit = Config.max_generated_bytes stream.config in
    if
      stream.generated_bytes > byte_limit
      || replacement_bytes > byte_limit - stream.generated_bytes
    then Error (generated_bytes stream origin replacement_bytes token.span)
    else
      let logical_path =
        match origin with
        | Text_definition definition ->
            Printf.sprintf "<definition:%08d:%s>" (Definition.id definition)
              (Definition.name definition)
        | Compiler_predefined predefined ->
            Printf.sprintf "<predefined:%s>" (Predefined.spelling predefined)
      in
      let source =
        Common.Source_manager.add_string stream.sources ~path:logical_path
          ~contents:replacement
      in
      stream.generated_bytes <- stream.generated_bytes + replacement_bytes;
      stream.current <-
        (match origin with
        | Text_definition definition ->
            Lexer_frame.push_definition ~caller:stream.current ~source
              ~definition ~invocation_span:token.span
        | Compiler_predefined predefined ->
            Lexer_frame.push_predefined ~caller:stream.current ~source
              ~predefined ~invocation_span:token.span);
      Ok ()

let predefined_replacement stream token predefined =
  let source = Lexer_frame.source stream.current in
  match Common.Source_file.position source token.Token.span.start with
  | Error message ->
      Error
        (diagnostic stream ~notes:[ message ] ~code:"HCPP0031"
           ~message:
             (Printf.sprintf
                "could not determine the source line for predefined value %S"
                (Predefined.spelling predefined))
           token.span)
  | Ok position ->
      Ok
        (Predefined.expand
           (Config.predefined stream.config)
           predefined ~source ~line:position.line
           ~source_depth:(Lexer_frame.source_depth stream.current))

let push_definition stream token definition =
  let id = Definition.id definition in
  match Lexer_frame.find_active_definition stream.current id with
  | Some _ -> Error (definition_cycle stream definition token.Token.span)
  | None -> (
      let predefined = Predefined.find (Definition.name definition) in
      match predefined with
      | Some predefined
        when Predefined.matches_standard_body predefined
               (Definition.replacement definition) ->
          Result.bind
            (predefined_replacement stream token predefined)
            (push_replacement stream token (Text_definition definition))
      | _ ->
          push_replacement stream token (Text_definition definition)
            (Definition.replacement definition))

let push_predefined stream token predefined =
  Result.bind
    (predefined_replacement stream token predefined)
    (push_replacement stream token (Compiler_predefined predefined))

let expand stream token =
  match definition_name token with
  | None -> Ok false
  | Some name -> (
      match Definition.Environment.find stream.definitions name with
      | None -> (
          match Predefined.find name with
          | None -> Ok false
          | Some predefined ->
              Result.map
                (fun () -> true)
                (push_predefined stream token predefined))
      | Some definition ->
          Result.map (fun () -> true) (push_definition stream token definition))

let rec next_expanded_source stream =
  match next_lexer_item stream with
  | Lexer.Diagnostic item ->
      let item = decorate_lexer_diagnostic stream item in
      Lexer.Diagnostic item
  | Lexer.Token token -> (
      match token.Token.kind with
      | Token_kind.Eof -> Lexer.Token token
      | Token_kind.Identifier | Token_kind.Keyword _ -> (
          match expand stream token with
          | Ok false -> Lexer.Token token
          | Ok true -> next_expanded_source stream
          | Error item -> Lexer.Diagnostic item)
      | _ -> Lexer.Token token)

let next_expanded stream =
  match stream.lookahead with
  | Some token ->
      stream.lookahead <- None;
      Lexer.Token token
  | None -> next_expanded_source stream

let retain_lookahead stream token =
  match stream.lookahead with
  | None -> stream.lookahead <- Some token
  | Some _ -> invalid_arg "preprocessor already has a retained token"

let include_path stream token =
  match token.Token.kind with
  | Token_kind.String -> (
      match token_text token with
      | Some spelling -> push_include stream token spelling
      | None -> Error (expected_directive stream token))
  | _ ->
      Error
        (diagnostic stream ~code:"HCPP0002"
           ~message:"expected a quoted path after #include" token.Token.span)

let invalid_help_argument stream token keyword =
  retain_lookahead stream token;
  diagnostic stream ~code:"HCPP0028"
    ~message:
      (Printf.sprintf "expected a string after #%s" (Keyword.spelling keyword))
    token.Token.span

let next_help_item stream context =
  let item = next_expanded stream in
  context :=
    merge_diagnostic_context !context (current_diagnostic_context stream);
  item

let help_provenance context ~directive_span ~value_spans :
    Help_metadata.provenance =
  {
    directive_span;
    value_spans;
    include_stack = context.include_stack;
    definition_trace = context.definition_trace;
  }

let record_help_index stream hash token =
  let context = ref (current_diagnostic_context stream) in
  let opener = directive_span hash token in
  match next_help_item stream context with
  | Lexer.Diagnostic item -> Error item
  | Lexer.Token first when first.Token.kind = Token_kind.String ->
      let buffer = Buffer.create 64 in
      Buffer.add_string buffer
        (Option.value (token_text first) ~default:first.Token.raw);
      let rec continue value_spans =
        match
          Lexer.consume_continuation_marker (Lexer_frame.lexer stream.current)
        with
        | None -> Ok (List.rev value_spans)
        | Some marker -> (
            match next_help_item stream context with
            | Lexer.Diagnostic item -> Error item
            | Lexer.Token fragment when fragment.Token.kind = Token_kind.String
              ->
                Buffer.add_string buffer
                  (Option.value (token_text fragment) ~default:fragment.raw);
                continue (fragment.span :: value_spans)
            | Lexer.Token lookahead ->
                retain_lookahead stream lookahead;
                let related : Common.Diagnostic.related =
                  {
                    span = marker;
                    message = "this continuation marker requests another string";
                  }
                in
                Error
                  (diagnostic stream ~context:!context ~secondary:[ related ]
                     ~code:"HCPP0029"
                     ~message:
                       "expected a string after the #help_index continuation"
                     lookahead.span))
      in
      Result.map
        (fun value_spans ->
          let provenance =
            help_provenance !context ~directive_span:opener ~value_spans
          in
          let entry : Help_metadata.index_entry =
            { value = Buffer.contents buffer; provenance }
          in
          stream.help_metadata <-
            Help_metadata.record_index stream.help_metadata entry)
        (continue [ first.span ])
  | Lexer.Token lookahead ->
      Error (invalid_help_argument stream lookahead Keyword.Help_index)

let record_help_file stream hash token =
  let context = ref (current_diagnostic_context stream) in
  let opener = directive_span hash token in
  match next_help_item stream context with
  | Lexer.Diagnostic item -> Error item
  | Lexer.Token path when path.Token.kind = Token_kind.String -> (
      let declared_path =
        Option.value (token_text path) ~default:path.Token.raw
      in
      let effective_path =
        Help_metadata.with_default_extension declared_path
        |> Help_metadata.sanitize_file_name
      in
      let resolver = Config.resolver stream.config in
      match
        Include_resolver.resolve_metadata resolver ~spelling:effective_path
      with
      | Error problem -> Error (help_path_problem stream path.span problem)
      | Ok resolution ->
          let provenance =
            help_provenance !context ~directive_span:opener
              ~value_spans:[ path.span ]
          in
          let entry : Help_metadata.file_entry =
            {
              declared_path;
              effective_path;
              resolved_path = resolution.resolved_path;
              source_link = Help_metadata.source_link stream.sources path.span;
              index = Help_metadata.current_index stream.help_metadata;
              provenance;
            }
          in
          stream.help_metadata <-
            Help_metadata.record_file stream.help_metadata entry;
          Ok ())
  | Lexer.Token lookahead ->
      Error (invalid_help_argument stream lookahead Keyword.Help_file)

let is_conditional_opener = function
  | Keyword.If | Keyword.Ifdef | Keyword.Ifndef | Keyword.Ifaot | Keyword.Ifjit
    -> true
  | _ -> false

let mode_condition stream = function
  | Keyword.Ifaot -> Config.compilation_mode stream.config = Aot
  | Keyword.Ifjit -> Config.compilation_mode stream.config = Jit
  | _ -> false

let symbol_present stream name =
  match Symbol_visibility.Environment.find_preprocessor stream.symbols name with
  | Symbol_visibility.Shadowed_by_local -> false
  | Symbol_visibility.Present _ -> true
  | Symbol_visibility.Absent ->
      Option.is_some (Definition.Environment.find stream.definitions name)
      || Option.is_some (Predefined.find name)

let expression_symbol_defined stream token =
  match definition_name token with
  | None -> false
  | Some name -> (
      match
        Symbol_visibility.Environment.find_preprocessor stream.symbols name
      with
      | Symbol_visibility.Present _ | Symbol_visibility.Shadowed_by_local ->
          true
      | Symbol_visibility.Absent -> false)

let expression_problem stream ?context
    (problem : Conditional_expression.problem) =
  diagnostic stream ?context ~secondary:problem.secondary ~notes:problem.notes
    ?help:problem.help ~code:problem.code ~message:problem.message
    problem.primary

let next_expression_item stream context =
  let item = next_expanded stream in
  context :=
    merge_diagnostic_context !context (current_diagnostic_context stream);
  item

let reject_conditional stream hash token keyword item =
  Result.bind
    (push_conditional ~parent_active:false ~valid:false stream hash token
       keyword false) (fun () -> Error item)

let enter_symbol_conditional stream hash token keyword =
  match next_unexpanded stream with
  | Lexer.Diagnostic item -> reject_conditional stream hash token keyword item
  | Lexer.Token name_token -> (
      match definition_name name_token with
      | Some name ->
          let present = symbol_present stream name in
          let condition =
            match keyword with
            | Keyword.Ifdef -> present
            | Keyword.Ifndef -> not present
            | _ -> invalid_arg "expected a symbol conditional"
          in
          push_conditional stream hash token keyword condition
      | None ->
          reject_conditional stream hash token keyword
            (invalid_symbol_condition_name stream name_token keyword))

let enter_expression_conditional stream hash token keyword =
  let context = ref (current_diagnostic_context stream) in
  match
    Conditional_expression.parse ~directive:Conditional_expression.If
      ~opener:(directive_span hash token)
      ~max_nodes:(Config.max_expression_nodes stream.config)
      ~next:(fun () -> next_expression_item stream context)
      ~symbol_defined:(expression_symbol_defined stream)
      ()
  with
  | Error (Conditional_expression.Lexer_diagnostic item) ->
      reject_conditional stream hash token keyword item
  | Error (Conditional_expression.Problem { problem; lookahead }) ->
      Option.iter (retain_lookahead stream) lookahead;
      reject_conditional stream hash token keyword
        (expression_problem stream ~context:!context problem)
  | Ok parsed -> (
      retain_lookahead stream (Conditional_expression.lookahead parsed);
      match Conditional_expression.evaluate parsed with
      | Ok value ->
          push_conditional stream hash token keyword
            (Conditional_expression.truthy value)
      | Error problem ->
          reject_conditional stream hash token keyword
            (expression_problem stream ~context:!context problem))

let assertion_warning stream ~context ~opener ~lookahead =
  let resume : Common.Diagnostic.related =
    {
      span = lookahead.Token.span;
      message = "preprocessing resumes with this token";
    }
  in
  diagnostic stream ~context ~secondary:[ resume ] ~code:"HCPP0024"
    ~severity:Common.Diagnostic.Warning
    ~message:"#assert expression evaluated to false" opener

let queue_diagnostic stream item =
  stream.pending_diagnostics <- stream.pending_diagnostics @ [ item ]

let evaluate_assertion stream hash token =
  let opener = directive_span hash token in
  let context = ref (current_diagnostic_context stream) in
  match
    Conditional_expression.parse ~directive:Conditional_expression.Assert
      ~opener
      ~max_nodes:(Config.max_expression_nodes stream.config)
      ~next:(fun () -> next_expression_item stream context)
      ~symbol_defined:(expression_symbol_defined stream)
      ()
  with
  | Error (Conditional_expression.Lexer_diagnostic item) -> Error item
  | Error (Conditional_expression.Problem { problem; lookahead }) ->
      Option.iter (retain_lookahead stream) lookahead;
      Error (expression_problem stream ~context:!context problem)
  | Ok parsed -> (
      let lookahead = Conditional_expression.lookahead parsed in
      retain_lookahead stream lookahead;
      match Conditional_expression.evaluate parsed with
      | Error problem ->
          Error (expression_problem stream ~context:!context problem)
      | Ok value ->
          if not (Conditional_expression.truthy value) then
            queue_diagnostic stream
              (assertion_warning stream ~context:!context ~opener ~lookahead);
          Ok ())

let enter_conditional stream ~inactive hash token keyword =
  match keyword with
  | Keyword.Ifaot | Keyword.Ifjit ->
      push_conditional stream hash token keyword (mode_condition stream keyword)
  | Keyword.Ifdef | Keyword.Ifndef ->
      if inactive then push_conditional stream hash token keyword false
      else enter_symbol_conditional stream hash token keyword
  | Keyword.If ->
      if inactive then push_conditional stream hash token keyword false
      else enter_expression_conditional stream hash token keyword
  | _ -> invalid_arg "expected a conditional opener"

let directive stream ~inactive hash =
  match next_expanded stream with
  | Lexer.Diagnostic item -> Error item
  | Lexer.Token token -> (
      match token.Token.kind with
      | Token_kind.Keyword keyword when is_conditional_opener keyword ->
          enter_conditional stream ~inactive hash token keyword
      | Token_kind.Keyword Keyword.Else -> conditional_else stream token
      | Token_kind.Keyword Keyword.Endif -> conditional_endif stream token
      | _ when inactive -> Ok ()
      | Token_kind.Keyword Keyword.Assert ->
          evaluate_assertion stream hash token
      | Token_kind.Keyword Keyword.Include -> (
          match next_expanded stream with
          | Lexer.Diagnostic item -> Error item
          | Lexer.Token path -> include_path stream path)
      | Token_kind.Keyword Keyword.Define -> define stream hash
      | Token_kind.Keyword Keyword.Help_index ->
          record_help_index stream hash token
      | Token_kind.Keyword Keyword.Help_file ->
          record_help_file stream hash token
      | Token_kind.Keyword keyword ->
          Error (unsupported_directive stream token keyword)
      | Token_kind.Identifier ->
          let spelling = Option.value (token_text token) ~default:token.raw in
          Error
            (diagnostic stream ~code:"HCPP0001"
               ~message:
                 (Printf.sprintf "unknown preprocessor directive #%s" spelling)
               token.span)
      | Token_kind.Eof -> Error (expected_directive stream hash)
      | _ -> Error (expected_directive stream token))

let finish_eof stream token =
  match finish_conditionals stream with
  | None -> Lexer.Token token
  | Some item -> Lexer.Diagnostic item

let rec next stream =
  match stream.pending_diagnostics with
  | item :: rest ->
      stream.pending_diagnostics <- rest;
      Lexer.Diagnostic item
  | [] ->
      if current_active stream then next_active stream else next_inactive stream

and next_active stream =
  match next_expanded stream with
  | Lexer.Token token when token.Token.kind = Token_kind.Punctuation '#' -> (
      match directive stream ~inactive:false token with
      | Ok () -> next stream
      | Error item -> Lexer.Diagnostic item)
  | Lexer.Token token when token.Token.kind = Token_kind.Eof ->
      finish_eof stream token
  | item -> item

and next_inactive stream =
  match stream.lookahead with
  | Some token ->
      stream.lookahead <- None;
      if token.Token.kind = Token_kind.Punctuation '#' then
        if stream.conditional_poisoned then next stream
        else
          match directive stream ~inactive:true token with
          | Ok () -> next stream
          | Error item -> Lexer.Diagnostic item
      else next_inactive stream
  | None -> (
      discard_exhausted_frames stream;
      match
        Lexer.scan_to_directive_marker (Lexer_frame.lexer stream.current)
      with
      | Error item ->
          align_current_to_source stream item.Common.Diagnostic.primary.source;
          let item = decorate_lexer_diagnostic stream item in
          discard_exhausted_frames stream;
          Lexer.Diagnostic item
      | Ok (Some hash) when stream.conditional_poisoned ->
          align_current_to_source stream hash.Token.span.source;
          discard_exhausted_frames stream;
          next stream
      | Ok (Some hash) -> (
          align_current_to_source stream hash.Token.span.source;
          discard_exhausted_frames stream;
          match directive stream ~inactive:true hash with
          | Ok () -> next stream
          | Error item -> Lexer.Diagnostic item)
      | Ok None -> (
          discard_exhausted_frames stream;
          match next_lexer_item stream with
          | Lexer.Token token -> finish_eof stream token
          | Lexer.Diagnostic item ->
              Lexer.Diagnostic (decorate_lexer_diagnostic stream item)))

let definitions stream = Definition.Environment.all stream.definitions

let definition_dump stream =
  Definition.Environment.dump stream.sources stream.definitions

let help_metadata (stream : t) = stream.help_metadata

let collect_all ~sources ~definitions ~symbols ~config source =
  let stream = create ~sources ~definitions ~symbols ~config source in
  let rec collect tokens diagnostics =
    match next stream with
    | Lexer.Token token when token.Token.kind = Token_kind.Eof ->
        {
          tokens = List.rev (token :: tokens);
          diagnostics = List.rev diagnostics;
          help_metadata = stream.help_metadata;
        }
    | Lexer.Token token -> collect (token :: tokens) diagnostics
    | Lexer.Diagnostic item -> collect tokens (item :: diagnostics)
  in
  collect [] []

let has_errors output =
  List.exists
    (fun item -> item.Common.Diagnostic.severity = Common.Diagnostic.Error)
    output.diagnostics

let lex_all ~sources ~definitions ~symbols ~config source =
  let output = collect_all ~sources ~definitions ~symbols ~config source in
  if has_errors output then Error output.diagnostics else Ok output.tokens
